// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package org.corps.bi.metrics.protobuf;

public interface AdTrackingProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metrics.AdTrackingProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  java.lang.String getClientId();
  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  java.lang.String getUserId();
  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string appkey = 5;</code>
   */
  java.lang.String getAppkey();
  /**
   * <code>string appkey = 5;</code>
   */
  com.google.protobuf.ByteString
      getAppkeyBytes();

  /**
   * <code>string mac = 6;</code>
   */
  java.lang.String getMac();
  /**
   * <code>string mac = 6;</code>
   */
  com.google.protobuf.ByteString
      getMacBytes();

  /**
   * <code>string macMd5 = 7;</code>
   */
  java.lang.String getMacMd5();
  /**
   * <code>string macMd5 = 7;</code>
   */
  com.google.protobuf.ByteString
      getMacMd5Bytes();

  /**
   * <code>string ifa = 8;</code>
   */
  java.lang.String getIfa();
  /**
   * <code>string ifa = 8;</code>
   */
  com.google.protobuf.ByteString
      getIfaBytes();

  /**
   * <code>string ifaMd5 = 9;</code>
   */
  java.lang.String getIfaMd5();
  /**
   * <code>string ifaMd5 = 9;</code>
   */
  com.google.protobuf.ByteString
      getIfaMd5Bytes();

  /**
   * <code>string uuid = 10;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 10;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   **
   * 格式是：yyyy-MM-dd HH:mm:ss
   * </pre>
   *
   * <code>int32 actType = 11;</code>
   */
  int getActType();

  /**
   * <code>string actTime = 13;</code>
   */
  java.lang.String getActTime();
  /**
   * <code>string actTime = 13;</code>
   */
  com.google.protobuf.ByteString
      getActTimeBytes();

  /**
   * <code>string pf = 14;</code>
   */
  java.lang.String getPf();
  /**
   * <code>string pf = 14;</code>
   */
  com.google.protobuf.ByteString
      getPfBytes();

  /**
   * <code>string ip = 15;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 15;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string userAgent = 16;</code>
   */
  java.lang.String getUserAgent();
  /**
   * <code>string userAgent = 16;</code>
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  /**
   * <code>string extra = 17;</code>
   */
  java.lang.String getExtra();
  /**
   * <code>string extra = 17;</code>
   */
  com.google.protobuf.ByteString
      getExtraBytes();

  /**
   * <code>string trackingDs = 18;</code>
   */
  java.lang.String getTrackingDs();
  /**
   * <code>string trackingDs = 18;</code>
   */
  com.google.protobuf.ByteString
      getTrackingDsBytes();

  /**
   * <code>int32 version = 19;</code>
   */
  int getVersion();

  /**
   * <code>string udid = 20;</code>
   */
  java.lang.String getUdid();
  /**
   * <code>string udid = 20;</code>
   */
  com.google.protobuf.ByteString
      getUdidBytes();

  /**
   * <code>string roleid = 21;</code>
   */
  java.lang.String getRoleid();
  /**
   * <code>string roleid = 21;</code>
   */
  com.google.protobuf.ByteString
      getRoleidBytes();
}
