// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package org.corps.bi.metrics.protobuf;

/**
 * Protobuf type {@code metrics.AdTrackingProto}
 */
public  final class AdTrackingProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:metrics.AdTrackingProto)
    AdTrackingProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdTrackingProto.newBuilder() to construct.
  private AdTrackingProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdTrackingProto() {
    clientId_ = "";
    userId_ = "";
    appkey_ = "";
    mac_ = "";
    macMd5_ = "";
    ifa_ = "";
    ifaMd5_ = "";
    uuid_ = "";
    actType_ = 0;
    actTime_ = "";
    pf_ = "";
    ip_ = "";
    userAgent_ = "";
    extra_ = "";
    trackingDs_ = "";
    version_ = 0;
    udid_ = "";
    roleid_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdTrackingProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            clientId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            appkey_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            mac_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            macMd5_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            ifa_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            ifaMd5_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            uuid_ = s;
            break;
          }
          case 88: {

            actType_ = input.readInt32();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            actTime_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            pf_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            userAgent_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            extra_ = s;
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            trackingDs_ = s;
            break;
          }
          case 152: {

            version_ = input.readInt32();
            break;
          }
          case 162: {
            java.lang.String s = input.readStringRequireUtf8();

            udid_ = s;
            break;
          }
          case 170: {
            java.lang.String s = input.readStringRequireUtf8();

            roleid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_AdTrackingProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_AdTrackingProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.corps.bi.metrics.protobuf.AdTrackingProto.class, org.corps.bi.metrics.protobuf.AdTrackingProto.Builder.class);
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object clientId_;
  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 4;
  private volatile java.lang.Object userId_;
  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPKEY_FIELD_NUMBER = 5;
  private volatile java.lang.Object appkey_;
  /**
   * <code>string appkey = 5;</code>
   */
  public java.lang.String getAppkey() {
    java.lang.Object ref = appkey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appkey_ = s;
      return s;
    }
  }
  /**
   * <code>string appkey = 5;</code>
   */
  public com.google.protobuf.ByteString
      getAppkeyBytes() {
    java.lang.Object ref = appkey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appkey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAC_FIELD_NUMBER = 6;
  private volatile java.lang.Object mac_;
  /**
   * <code>string mac = 6;</code>
   */
  public java.lang.String getMac() {
    java.lang.Object ref = mac_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mac_ = s;
      return s;
    }
  }
  /**
   * <code>string mac = 6;</code>
   */
  public com.google.protobuf.ByteString
      getMacBytes() {
    java.lang.Object ref = mac_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mac_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MACMD5_FIELD_NUMBER = 7;
  private volatile java.lang.Object macMd5_;
  /**
   * <code>string macMd5 = 7;</code>
   */
  public java.lang.String getMacMd5() {
    java.lang.Object ref = macMd5_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      macMd5_ = s;
      return s;
    }
  }
  /**
   * <code>string macMd5 = 7;</code>
   */
  public com.google.protobuf.ByteString
      getMacMd5Bytes() {
    java.lang.Object ref = macMd5_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      macMd5_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IFA_FIELD_NUMBER = 8;
  private volatile java.lang.Object ifa_;
  /**
   * <code>string ifa = 8;</code>
   */
  public java.lang.String getIfa() {
    java.lang.Object ref = ifa_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ifa_ = s;
      return s;
    }
  }
  /**
   * <code>string ifa = 8;</code>
   */
  public com.google.protobuf.ByteString
      getIfaBytes() {
    java.lang.Object ref = ifa_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ifa_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IFAMD5_FIELD_NUMBER = 9;
  private volatile java.lang.Object ifaMd5_;
  /**
   * <code>string ifaMd5 = 9;</code>
   */
  public java.lang.String getIfaMd5() {
    java.lang.Object ref = ifaMd5_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ifaMd5_ = s;
      return s;
    }
  }
  /**
   * <code>string ifaMd5 = 9;</code>
   */
  public com.google.protobuf.ByteString
      getIfaMd5Bytes() {
    java.lang.Object ref = ifaMd5_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ifaMd5_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UUID_FIELD_NUMBER = 10;
  private volatile java.lang.Object uuid_;
  /**
   * <code>string uuid = 10;</code>
   */
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 10;</code>
   */
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTTYPE_FIELD_NUMBER = 11;
  private int actType_;
  /**
   * <pre>
   **
   * 格式是：yyyy-MM-dd HH:mm:ss
   * </pre>
   *
   * <code>int32 actType = 11;</code>
   */
  public int getActType() {
    return actType_;
  }

  public static final int ACTTIME_FIELD_NUMBER = 13;
  private volatile java.lang.Object actTime_;
  /**
   * <code>string actTime = 13;</code>
   */
  public java.lang.String getActTime() {
    java.lang.Object ref = actTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actTime_ = s;
      return s;
    }
  }
  /**
   * <code>string actTime = 13;</code>
   */
  public com.google.protobuf.ByteString
      getActTimeBytes() {
    java.lang.Object ref = actTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PF_FIELD_NUMBER = 14;
  private volatile java.lang.Object pf_;
  /**
   * <code>string pf = 14;</code>
   */
  public java.lang.String getPf() {
    java.lang.Object ref = pf_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pf_ = s;
      return s;
    }
  }
  /**
   * <code>string pf = 14;</code>
   */
  public com.google.protobuf.ByteString
      getPfBytes() {
    java.lang.Object ref = pf_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pf_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_FIELD_NUMBER = 15;
  private volatile java.lang.Object ip_;
  /**
   * <code>string ip = 15;</code>
   */
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>string ip = 15;</code>
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERAGENT_FIELD_NUMBER = 16;
  private volatile java.lang.Object userAgent_;
  /**
   * <code>string userAgent = 16;</code>
   */
  public java.lang.String getUserAgent() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userAgent_ = s;
      return s;
    }
  }
  /**
   * <code>string userAgent = 16;</code>
   */
  public com.google.protobuf.ByteString
      getUserAgentBytes() {
    java.lang.Object ref = userAgent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userAgent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRA_FIELD_NUMBER = 17;
  private volatile java.lang.Object extra_;
  /**
   * <code>string extra = 17;</code>
   */
  public java.lang.String getExtra() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extra_ = s;
      return s;
    }
  }
  /**
   * <code>string extra = 17;</code>
   */
  public com.google.protobuf.ByteString
      getExtraBytes() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACKINGDS_FIELD_NUMBER = 18;
  private volatile java.lang.Object trackingDs_;
  /**
   * <code>string trackingDs = 18;</code>
   */
  public java.lang.String getTrackingDs() {
    java.lang.Object ref = trackingDs_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      trackingDs_ = s;
      return s;
    }
  }
  /**
   * <code>string trackingDs = 18;</code>
   */
  public com.google.protobuf.ByteString
      getTrackingDsBytes() {
    java.lang.Object ref = trackingDs_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      trackingDs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 19;
  private int version_;
  /**
   * <code>int32 version = 19;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int UDID_FIELD_NUMBER = 20;
  private volatile java.lang.Object udid_;
  /**
   * <code>string udid = 20;</code>
   */
  public java.lang.String getUdid() {
    java.lang.Object ref = udid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      udid_ = s;
      return s;
    }
  }
  /**
   * <code>string udid = 20;</code>
   */
  public com.google.protobuf.ByteString
      getUdidBytes() {
    java.lang.Object ref = udid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      udid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLEID_FIELD_NUMBER = 21;
  private volatile java.lang.Object roleid_;
  /**
   * <code>string roleid = 21;</code>
   */
  public java.lang.String getRoleid() {
    java.lang.Object ref = roleid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roleid_ = s;
      return s;
    }
  }
  /**
   * <code>string roleid = 21;</code>
   */
  public com.google.protobuf.ByteString
      getRoleidBytes() {
    java.lang.Object ref = roleid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roleid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
    }
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userId_);
    }
    if (!getAppkeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, appkey_);
    }
    if (!getMacBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, mac_);
    }
    if (!getMacMd5Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, macMd5_);
    }
    if (!getIfaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, ifa_);
    }
    if (!getIfaMd5Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, ifaMd5_);
    }
    if (!getUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, uuid_);
    }
    if (actType_ != 0) {
      output.writeInt32(11, actType_);
    }
    if (!getActTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, actTime_);
    }
    if (!getPfBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, pf_);
    }
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, ip_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, userAgent_);
    }
    if (!getExtraBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, extra_);
    }
    if (!getTrackingDsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, trackingDs_);
    }
    if (version_ != 0) {
      output.writeInt32(19, version_);
    }
    if (!getUdidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, udid_);
    }
    if (!getRoleidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 21, roleid_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
    }
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userId_);
    }
    if (!getAppkeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, appkey_);
    }
    if (!getMacBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, mac_);
    }
    if (!getMacMd5Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, macMd5_);
    }
    if (!getIfaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, ifa_);
    }
    if (!getIfaMd5Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, ifaMd5_);
    }
    if (!getUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, uuid_);
    }
    if (actType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, actType_);
    }
    if (!getActTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, actTime_);
    }
    if (!getPfBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, pf_);
    }
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, ip_);
    }
    if (!getUserAgentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, userAgent_);
    }
    if (!getExtraBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, extra_);
    }
    if (!getTrackingDsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, trackingDs_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(19, version_);
    }
    if (!getUdidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, udid_);
    }
    if (!getRoleidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, roleid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.corps.bi.metrics.protobuf.AdTrackingProto)) {
      return super.equals(obj);
    }
    org.corps.bi.metrics.protobuf.AdTrackingProto other = (org.corps.bi.metrics.protobuf.AdTrackingProto) obj;

    boolean result = true;
    result = result && getClientId()
        .equals(other.getClientId());
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && getAppkey()
        .equals(other.getAppkey());
    result = result && getMac()
        .equals(other.getMac());
    result = result && getMacMd5()
        .equals(other.getMacMd5());
    result = result && getIfa()
        .equals(other.getIfa());
    result = result && getIfaMd5()
        .equals(other.getIfaMd5());
    result = result && getUuid()
        .equals(other.getUuid());
    result = result && (getActType()
        == other.getActType());
    result = result && getActTime()
        .equals(other.getActTime());
    result = result && getPf()
        .equals(other.getPf());
    result = result && getIp()
        .equals(other.getIp());
    result = result && getUserAgent()
        .equals(other.getUserAgent());
    result = result && getExtra()
        .equals(other.getExtra());
    result = result && getTrackingDs()
        .equals(other.getTrackingDs());
    result = result && (getVersion()
        == other.getVersion());
    result = result && getUdid()
        .equals(other.getUdid());
    result = result && getRoleid()
        .equals(other.getRoleid());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + APPKEY_FIELD_NUMBER;
    hash = (53 * hash) + getAppkey().hashCode();
    hash = (37 * hash) + MAC_FIELD_NUMBER;
    hash = (53 * hash) + getMac().hashCode();
    hash = (37 * hash) + MACMD5_FIELD_NUMBER;
    hash = (53 * hash) + getMacMd5().hashCode();
    hash = (37 * hash) + IFA_FIELD_NUMBER;
    hash = (53 * hash) + getIfa().hashCode();
    hash = (37 * hash) + IFAMD5_FIELD_NUMBER;
    hash = (53 * hash) + getIfaMd5().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (37 * hash) + ACTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getActType();
    hash = (37 * hash) + ACTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getActTime().hashCode();
    hash = (37 * hash) + PF_FIELD_NUMBER;
    hash = (53 * hash) + getPf().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
    hash = (53 * hash) + getUserAgent().hashCode();
    hash = (37 * hash) + EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getExtra().hashCode();
    hash = (37 * hash) + TRACKINGDS_FIELD_NUMBER;
    hash = (53 * hash) + getTrackingDs().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + UDID_FIELD_NUMBER;
    hash = (53 * hash) + getUdid().hashCode();
    hash = (37 * hash) + ROLEID_FIELD_NUMBER;
    hash = (53 * hash) + getRoleid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.corps.bi.metrics.protobuf.AdTrackingProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.corps.bi.metrics.protobuf.AdTrackingProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code metrics.AdTrackingProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:metrics.AdTrackingProto)
      org.corps.bi.metrics.protobuf.AdTrackingProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_AdTrackingProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_AdTrackingProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.corps.bi.metrics.protobuf.AdTrackingProto.class, org.corps.bi.metrics.protobuf.AdTrackingProto.Builder.class);
    }

    // Construct using org.corps.bi.metrics.protobuf.AdTrackingProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      clientId_ = "";

      userId_ = "";

      appkey_ = "";

      mac_ = "";

      macMd5_ = "";

      ifa_ = "";

      ifaMd5_ = "";

      uuid_ = "";

      actType_ = 0;

      actTime_ = "";

      pf_ = "";

      ip_ = "";

      userAgent_ = "";

      extra_ = "";

      trackingDs_ = "";

      version_ = 0;

      udid_ = "";

      roleid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_AdTrackingProto_descriptor;
    }

    public org.corps.bi.metrics.protobuf.AdTrackingProto getDefaultInstanceForType() {
      return org.corps.bi.metrics.protobuf.AdTrackingProto.getDefaultInstance();
    }

    public org.corps.bi.metrics.protobuf.AdTrackingProto build() {
      org.corps.bi.metrics.protobuf.AdTrackingProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.corps.bi.metrics.protobuf.AdTrackingProto buildPartial() {
      org.corps.bi.metrics.protobuf.AdTrackingProto result = new org.corps.bi.metrics.protobuf.AdTrackingProto(this);
      result.clientId_ = clientId_;
      result.userId_ = userId_;
      result.appkey_ = appkey_;
      result.mac_ = mac_;
      result.macMd5_ = macMd5_;
      result.ifa_ = ifa_;
      result.ifaMd5_ = ifaMd5_;
      result.uuid_ = uuid_;
      result.actType_ = actType_;
      result.actTime_ = actTime_;
      result.pf_ = pf_;
      result.ip_ = ip_;
      result.userAgent_ = userAgent_;
      result.extra_ = extra_;
      result.trackingDs_ = trackingDs_;
      result.version_ = version_;
      result.udid_ = udid_;
      result.roleid_ = roleid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.corps.bi.metrics.protobuf.AdTrackingProto) {
        return mergeFrom((org.corps.bi.metrics.protobuf.AdTrackingProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.corps.bi.metrics.protobuf.AdTrackingProto other) {
      if (other == org.corps.bi.metrics.protobuf.AdTrackingProto.getDefaultInstance()) return this;
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getAppkey().isEmpty()) {
        appkey_ = other.appkey_;
        onChanged();
      }
      if (!other.getMac().isEmpty()) {
        mac_ = other.mac_;
        onChanged();
      }
      if (!other.getMacMd5().isEmpty()) {
        macMd5_ = other.macMd5_;
        onChanged();
      }
      if (!other.getIfa().isEmpty()) {
        ifa_ = other.ifa_;
        onChanged();
      }
      if (!other.getIfaMd5().isEmpty()) {
        ifaMd5_ = other.ifaMd5_;
        onChanged();
      }
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      if (other.getActType() != 0) {
        setActType(other.getActType());
      }
      if (!other.getActTime().isEmpty()) {
        actTime_ = other.actTime_;
        onChanged();
      }
      if (!other.getPf().isEmpty()) {
        pf_ = other.pf_;
        onChanged();
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (!other.getUserAgent().isEmpty()) {
        userAgent_ = other.userAgent_;
        onChanged();
      }
      if (!other.getExtra().isEmpty()) {
        extra_ = other.extra_;
        onChanged();
      }
      if (!other.getTrackingDs().isEmpty()) {
        trackingDs_ = other.trackingDs_;
        onChanged();
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (!other.getUdid().isEmpty()) {
        udid_ = other.udid_;
        onChanged();
      }
      if (!other.getRoleid().isEmpty()) {
        roleid_ = other.roleid_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.corps.bi.metrics.protobuf.AdTrackingProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.corps.bi.metrics.protobuf.AdTrackingProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clientId_ = "";
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public Builder clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appkey_ = "";
    /**
     * <code>string appkey = 5;</code>
     */
    public java.lang.String getAppkey() {
      java.lang.Object ref = appkey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appkey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string appkey = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAppkeyBytes() {
      java.lang.Object ref = appkey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appkey = 5;</code>
     */
    public Builder setAppkey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appkey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string appkey = 5;</code>
     */
    public Builder clearAppkey() {
      
      appkey_ = getDefaultInstance().getAppkey();
      onChanged();
      return this;
    }
    /**
     * <code>string appkey = 5;</code>
     */
    public Builder setAppkeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appkey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mac_ = "";
    /**
     * <code>string mac = 6;</code>
     */
    public java.lang.String getMac() {
      java.lang.Object ref = mac_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mac_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mac = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMacBytes() {
      java.lang.Object ref = mac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mac = 6;</code>
     */
    public Builder setMac(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mac_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mac = 6;</code>
     */
    public Builder clearMac() {
      
      mac_ = getDefaultInstance().getMac();
      onChanged();
      return this;
    }
    /**
     * <code>string mac = 6;</code>
     */
    public Builder setMacBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mac_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object macMd5_ = "";
    /**
     * <code>string macMd5 = 7;</code>
     */
    public java.lang.String getMacMd5() {
      java.lang.Object ref = macMd5_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        macMd5_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string macMd5 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMacMd5Bytes() {
      java.lang.Object ref = macMd5_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        macMd5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string macMd5 = 7;</code>
     */
    public Builder setMacMd5(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      macMd5_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string macMd5 = 7;</code>
     */
    public Builder clearMacMd5() {
      
      macMd5_ = getDefaultInstance().getMacMd5();
      onChanged();
      return this;
    }
    /**
     * <code>string macMd5 = 7;</code>
     */
    public Builder setMacMd5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      macMd5_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ifa_ = "";
    /**
     * <code>string ifa = 8;</code>
     */
    public java.lang.String getIfa() {
      java.lang.Object ref = ifa_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ifa_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ifa = 8;</code>
     */
    public com.google.protobuf.ByteString
        getIfaBytes() {
      java.lang.Object ref = ifa_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ifa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ifa = 8;</code>
     */
    public Builder setIfa(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ifa_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ifa = 8;</code>
     */
    public Builder clearIfa() {
      
      ifa_ = getDefaultInstance().getIfa();
      onChanged();
      return this;
    }
    /**
     * <code>string ifa = 8;</code>
     */
    public Builder setIfaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ifa_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ifaMd5_ = "";
    /**
     * <code>string ifaMd5 = 9;</code>
     */
    public java.lang.String getIfaMd5() {
      java.lang.Object ref = ifaMd5_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ifaMd5_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ifaMd5 = 9;</code>
     */
    public com.google.protobuf.ByteString
        getIfaMd5Bytes() {
      java.lang.Object ref = ifaMd5_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ifaMd5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ifaMd5 = 9;</code>
     */
    public Builder setIfaMd5(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ifaMd5_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ifaMd5 = 9;</code>
     */
    public Builder clearIfaMd5() {
      
      ifaMd5_ = getDefaultInstance().getIfaMd5();
      onChanged();
      return this;
    }
    /**
     * <code>string ifaMd5 = 9;</code>
     */
    public Builder setIfaMd5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ifaMd5_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 10;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 10;</code>
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 10;</code>
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 10;</code>
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }

    private int actType_ ;
    /**
     * <pre>
     **
     * 格式是：yyyy-MM-dd HH:mm:ss
     * </pre>
     *
     * <code>int32 actType = 11;</code>
     */
    public int getActType() {
      return actType_;
    }
    /**
     * <pre>
     **
     * 格式是：yyyy-MM-dd HH:mm:ss
     * </pre>
     *
     * <code>int32 actType = 11;</code>
     */
    public Builder setActType(int value) {
      
      actType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 格式是：yyyy-MM-dd HH:mm:ss
     * </pre>
     *
     * <code>int32 actType = 11;</code>
     */
    public Builder clearActType() {
      
      actType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object actTime_ = "";
    /**
     * <code>string actTime = 13;</code>
     */
    public java.lang.String getActTime() {
      java.lang.Object ref = actTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string actTime = 13;</code>
     */
    public com.google.protobuf.ByteString
        getActTimeBytes() {
      java.lang.Object ref = actTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string actTime = 13;</code>
     */
    public Builder setActTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      actTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string actTime = 13;</code>
     */
    public Builder clearActTime() {
      
      actTime_ = getDefaultInstance().getActTime();
      onChanged();
      return this;
    }
    /**
     * <code>string actTime = 13;</code>
     */
    public Builder setActTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      actTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pf_ = "";
    /**
     * <code>string pf = 14;</code>
     */
    public java.lang.String getPf() {
      java.lang.Object ref = pf_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pf_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pf = 14;</code>
     */
    public com.google.protobuf.ByteString
        getPfBytes() {
      java.lang.Object ref = pf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pf = 14;</code>
     */
    public Builder setPf(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pf_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pf = 14;</code>
     */
    public Builder clearPf() {
      
      pf_ = getDefaultInstance().getPf();
      onChanged();
      return this;
    }
    /**
     * <code>string pf = 14;</code>
     */
    public Builder setPfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pf_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <code>string ip = 15;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ip = 15;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ip = 15;</code>
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 15;</code>
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 15;</code>
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userAgent_ = "";
    /**
     * <code>string userAgent = 16;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userAgent = 16;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userAgent = 16;</code>
     */
    public Builder setUserAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userAgent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userAgent = 16;</code>
     */
    public Builder clearUserAgent() {
      
      userAgent_ = getDefaultInstance().getUserAgent();
      onChanged();
      return this;
    }
    /**
     * <code>string userAgent = 16;</code>
     */
    public Builder setUserAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userAgent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object extra_ = "";
    /**
     * <code>string extra = 17;</code>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extra = 17;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extra = 17;</code>
     */
    public Builder setExtra(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extra_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 17;</code>
     */
    public Builder clearExtra() {
      
      extra_ = getDefaultInstance().getExtra();
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 17;</code>
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extra_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object trackingDs_ = "";
    /**
     * <code>string trackingDs = 18;</code>
     */
    public java.lang.String getTrackingDs() {
      java.lang.Object ref = trackingDs_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        trackingDs_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string trackingDs = 18;</code>
     */
    public com.google.protobuf.ByteString
        getTrackingDsBytes() {
      java.lang.Object ref = trackingDs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trackingDs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string trackingDs = 18;</code>
     */
    public Builder setTrackingDs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      trackingDs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string trackingDs = 18;</code>
     */
    public Builder clearTrackingDs() {
      
      trackingDs_ = getDefaultInstance().getTrackingDs();
      onChanged();
      return this;
    }
    /**
     * <code>string trackingDs = 18;</code>
     */
    public Builder setTrackingDsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      trackingDs_ = value;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 19;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 19;</code>
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 19;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object udid_ = "";
    /**
     * <code>string udid = 20;</code>
     */
    public java.lang.String getUdid() {
      java.lang.Object ref = udid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        udid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string udid = 20;</code>
     */
    public com.google.protobuf.ByteString
        getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string udid = 20;</code>
     */
    public Builder setUdid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      udid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string udid = 20;</code>
     */
    public Builder clearUdid() {
      
      udid_ = getDefaultInstance().getUdid();
      onChanged();
      return this;
    }
    /**
     * <code>string udid = 20;</code>
     */
    public Builder setUdidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      udid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object roleid_ = "";
    /**
     * <code>string roleid = 21;</code>
     */
    public java.lang.String getRoleid() {
      java.lang.Object ref = roleid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roleid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string roleid = 21;</code>
     */
    public com.google.protobuf.ByteString
        getRoleidBytes() {
      java.lang.Object ref = roleid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string roleid = 21;</code>
     */
    public Builder setRoleid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roleid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string roleid = 21;</code>
     */
    public Builder clearRoleid() {
      
      roleid_ = getDefaultInstance().getRoleid();
      onChanged();
      return this;
    }
    /**
     * <code>string roleid = 21;</code>
     */
    public Builder setRoleidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roleid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:metrics.AdTrackingProto)
  }

  // @@protoc_insertion_point(class_scope:metrics.AdTrackingProto)
  private static final org.corps.bi.metrics.protobuf.AdTrackingProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.corps.bi.metrics.protobuf.AdTrackingProto();
  }

  public static org.corps.bi.metrics.protobuf.AdTrackingProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdTrackingProto>
      PARSER = new com.google.protobuf.AbstractParser<AdTrackingProto>() {
    public AdTrackingProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdTrackingProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdTrackingProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdTrackingProto> getParserForType() {
    return PARSER;
  }

  public org.corps.bi.metrics.protobuf.AdTrackingProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

