// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package org.corps.bi.metrics.protobuf;

/**
 * Protobuf type {@code metrics.CustomBinaryBodyMetricProto}
 */
public  final class CustomBinaryBodyMetricProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:metrics.CustomBinaryBodyMetricProto)
    CustomBinaryBodyMetricProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CustomBinaryBodyMetricProto.newBuilder() to construct.
  private CustomBinaryBodyMetricProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CustomBinaryBodyMetricProto() {
    clientId_ = "";
    userId_ = "";
    customMetircName_ = "";
    metricDate_ = "";
    metricTime_ = "";
    body_ = com.google.protobuf.ByteString.EMPTY;
    extra_ = "";
    version_ = 0;
    udid_ = "";
    roleid_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CustomBinaryBodyMetricProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            clientId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            customMetircName_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            metricDate_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            metricTime_ = s;
            break;
          }
          case 66: {

            body_ = input.readBytes();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            extra_ = s;
            break;
          }
          case 80: {

            version_ = input.readInt32();
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            udid_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            roleid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_CustomBinaryBodyMetricProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_CustomBinaryBodyMetricProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto.class, org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto.Builder.class);
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object clientId_;
  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 4;
  private volatile java.lang.Object userId_;
  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMMETIRCNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object customMetircName_;
  /**
   * <code>string customMetircName = 5;</code>
   */
  public java.lang.String getCustomMetircName() {
    java.lang.Object ref = customMetircName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customMetircName_ = s;
      return s;
    }
  }
  /**
   * <code>string customMetircName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCustomMetircNameBytes() {
    java.lang.Object ref = customMetircName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customMetircName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METRICDATE_FIELD_NUMBER = 6;
  private volatile java.lang.Object metricDate_;
  /**
   * <code>string metricDate = 6;</code>
   */
  public java.lang.String getMetricDate() {
    java.lang.Object ref = metricDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metricDate_ = s;
      return s;
    }
  }
  /**
   * <code>string metricDate = 6;</code>
   */
  public com.google.protobuf.ByteString
      getMetricDateBytes() {
    java.lang.Object ref = metricDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metricDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METRICTIME_FIELD_NUMBER = 7;
  private volatile java.lang.Object metricTime_;
  /**
   * <code>string metricTime = 7;</code>
   */
  public java.lang.String getMetricTime() {
    java.lang.Object ref = metricTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metricTime_ = s;
      return s;
    }
  }
  /**
   * <code>string metricTime = 7;</code>
   */
  public com.google.protobuf.ByteString
      getMetricTimeBytes() {
    java.lang.Object ref = metricTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metricTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString body_;
  /**
   * <code>bytes body = 8;</code>
   */
  public com.google.protobuf.ByteString getBody() {
    return body_;
  }

  public static final int EXTRA_FIELD_NUMBER = 9;
  private volatile java.lang.Object extra_;
  /**
   * <code>string extra = 9;</code>
   */
  public java.lang.String getExtra() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extra_ = s;
      return s;
    }
  }
  /**
   * <code>string extra = 9;</code>
   */
  public com.google.protobuf.ByteString
      getExtraBytes() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 10;
  private int version_;
  /**
   * <code>int32 version = 10;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int UDID_FIELD_NUMBER = 11;
  private volatile java.lang.Object udid_;
  /**
   * <code>string udid = 11;</code>
   */
  public java.lang.String getUdid() {
    java.lang.Object ref = udid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      udid_ = s;
      return s;
    }
  }
  /**
   * <code>string udid = 11;</code>
   */
  public com.google.protobuf.ByteString
      getUdidBytes() {
    java.lang.Object ref = udid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      udid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLEID_FIELD_NUMBER = 12;
  private volatile java.lang.Object roleid_;
  /**
   * <code>string roleid = 12;</code>
   */
  public java.lang.String getRoleid() {
    java.lang.Object ref = roleid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roleid_ = s;
      return s;
    }
  }
  /**
   * <code>string roleid = 12;</code>
   */
  public com.google.protobuf.ByteString
      getRoleidBytes() {
    java.lang.Object ref = roleid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roleid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
    }
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userId_);
    }
    if (!getCustomMetircNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, customMetircName_);
    }
    if (!getMetricDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, metricDate_);
    }
    if (!getMetricTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, metricTime_);
    }
    if (!body_.isEmpty()) {
      output.writeBytes(8, body_);
    }
    if (!getExtraBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, extra_);
    }
    if (version_ != 0) {
      output.writeInt32(10, version_);
    }
    if (!getUdidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, udid_);
    }
    if (!getRoleidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, roleid_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
    }
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userId_);
    }
    if (!getCustomMetircNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, customMetircName_);
    }
    if (!getMetricDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, metricDate_);
    }
    if (!getMetricTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, metricTime_);
    }
    if (!body_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, body_);
    }
    if (!getExtraBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, extra_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, version_);
    }
    if (!getUdidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, udid_);
    }
    if (!getRoleidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, roleid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto)) {
      return super.equals(obj);
    }
    org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto other = (org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto) obj;

    boolean result = true;
    result = result && getClientId()
        .equals(other.getClientId());
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && getCustomMetircName()
        .equals(other.getCustomMetircName());
    result = result && getMetricDate()
        .equals(other.getMetricDate());
    result = result && getMetricTime()
        .equals(other.getMetricTime());
    result = result && getBody()
        .equals(other.getBody());
    result = result && getExtra()
        .equals(other.getExtra());
    result = result && (getVersion()
        == other.getVersion());
    result = result && getUdid()
        .equals(other.getUdid());
    result = result && getRoleid()
        .equals(other.getRoleid());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + CUSTOMMETIRCNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCustomMetircName().hashCode();
    hash = (37 * hash) + METRICDATE_FIELD_NUMBER;
    hash = (53 * hash) + getMetricDate().hashCode();
    hash = (37 * hash) + METRICTIME_FIELD_NUMBER;
    hash = (53 * hash) + getMetricTime().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getExtra().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + UDID_FIELD_NUMBER;
    hash = (53 * hash) + getUdid().hashCode();
    hash = (37 * hash) + ROLEID_FIELD_NUMBER;
    hash = (53 * hash) + getRoleid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code metrics.CustomBinaryBodyMetricProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:metrics.CustomBinaryBodyMetricProto)
      org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_CustomBinaryBodyMetricProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_CustomBinaryBodyMetricProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto.class, org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto.Builder.class);
    }

    // Construct using org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      clientId_ = "";

      userId_ = "";

      customMetircName_ = "";

      metricDate_ = "";

      metricTime_ = "";

      body_ = com.google.protobuf.ByteString.EMPTY;

      extra_ = "";

      version_ = 0;

      udid_ = "";

      roleid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_CustomBinaryBodyMetricProto_descriptor;
    }

    public org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto getDefaultInstanceForType() {
      return org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto.getDefaultInstance();
    }

    public org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto build() {
      org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto buildPartial() {
      org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto result = new org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto(this);
      result.clientId_ = clientId_;
      result.userId_ = userId_;
      result.customMetircName_ = customMetircName_;
      result.metricDate_ = metricDate_;
      result.metricTime_ = metricTime_;
      result.body_ = body_;
      result.extra_ = extra_;
      result.version_ = version_;
      result.udid_ = udid_;
      result.roleid_ = roleid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto) {
        return mergeFrom((org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto other) {
      if (other == org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto.getDefaultInstance()) return this;
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getCustomMetircName().isEmpty()) {
        customMetircName_ = other.customMetircName_;
        onChanged();
      }
      if (!other.getMetricDate().isEmpty()) {
        metricDate_ = other.metricDate_;
        onChanged();
      }
      if (!other.getMetricTime().isEmpty()) {
        metricTime_ = other.metricTime_;
        onChanged();
      }
      if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
        setBody(other.getBody());
      }
      if (!other.getExtra().isEmpty()) {
        extra_ = other.extra_;
        onChanged();
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (!other.getUdid().isEmpty()) {
        udid_ = other.udid_;
        onChanged();
      }
      if (!other.getRoleid().isEmpty()) {
        roleid_ = other.roleid_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clientId_ = "";
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public Builder clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object customMetircName_ = "";
    /**
     * <code>string customMetircName = 5;</code>
     */
    public java.lang.String getCustomMetircName() {
      java.lang.Object ref = customMetircName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customMetircName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string customMetircName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCustomMetircNameBytes() {
      java.lang.Object ref = customMetircName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customMetircName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customMetircName = 5;</code>
     */
    public Builder setCustomMetircName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customMetircName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customMetircName = 5;</code>
     */
    public Builder clearCustomMetircName() {
      
      customMetircName_ = getDefaultInstance().getCustomMetircName();
      onChanged();
      return this;
    }
    /**
     * <code>string customMetircName = 5;</code>
     */
    public Builder setCustomMetircNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customMetircName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object metricDate_ = "";
    /**
     * <code>string metricDate = 6;</code>
     */
    public java.lang.String getMetricDate() {
      java.lang.Object ref = metricDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metricDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string metricDate = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMetricDateBytes() {
      java.lang.Object ref = metricDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metricDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string metricDate = 6;</code>
     */
    public Builder setMetricDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metricDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string metricDate = 6;</code>
     */
    public Builder clearMetricDate() {
      
      metricDate_ = getDefaultInstance().getMetricDate();
      onChanged();
      return this;
    }
    /**
     * <code>string metricDate = 6;</code>
     */
    public Builder setMetricDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metricDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object metricTime_ = "";
    /**
     * <code>string metricTime = 7;</code>
     */
    public java.lang.String getMetricTime() {
      java.lang.Object ref = metricTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metricTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string metricTime = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMetricTimeBytes() {
      java.lang.Object ref = metricTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metricTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string metricTime = 7;</code>
     */
    public Builder setMetricTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metricTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string metricTime = 7;</code>
     */
    public Builder clearMetricTime() {
      
      metricTime_ = getDefaultInstance().getMetricTime();
      onChanged();
      return this;
    }
    /**
     * <code>string metricTime = 7;</code>
     */
    public Builder setMetricTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metricTime_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes body = 8;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>bytes body = 8;</code>
     */
    public Builder setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes body = 8;</code>
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }

    private java.lang.Object extra_ = "";
    /**
     * <code>string extra = 9;</code>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extra = 9;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extra = 9;</code>
     */
    public Builder setExtra(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extra_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 9;</code>
     */
    public Builder clearExtra() {
      
      extra_ = getDefaultInstance().getExtra();
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 9;</code>
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extra_ = value;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 10;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 10;</code>
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 10;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object udid_ = "";
    /**
     * <code>string udid = 11;</code>
     */
    public java.lang.String getUdid() {
      java.lang.Object ref = udid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        udid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string udid = 11;</code>
     */
    public com.google.protobuf.ByteString
        getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string udid = 11;</code>
     */
    public Builder setUdid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      udid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string udid = 11;</code>
     */
    public Builder clearUdid() {
      
      udid_ = getDefaultInstance().getUdid();
      onChanged();
      return this;
    }
    /**
     * <code>string udid = 11;</code>
     */
    public Builder setUdidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      udid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object roleid_ = "";
    /**
     * <code>string roleid = 12;</code>
     */
    public java.lang.String getRoleid() {
      java.lang.Object ref = roleid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roleid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string roleid = 12;</code>
     */
    public com.google.protobuf.ByteString
        getRoleidBytes() {
      java.lang.Object ref = roleid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string roleid = 12;</code>
     */
    public Builder setRoleid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roleid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string roleid = 12;</code>
     */
    public Builder clearRoleid() {
      
      roleid_ = getDefaultInstance().getRoleid();
      onChanged();
      return this;
    }
    /**
     * <code>string roleid = 12;</code>
     */
    public Builder setRoleidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roleid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:metrics.CustomBinaryBodyMetricProto)
  }

  // @@protoc_insertion_point(class_scope:metrics.CustomBinaryBodyMetricProto)
  private static final org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto();
  }

  public static org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CustomBinaryBodyMetricProto>
      PARSER = new com.google.protobuf.AbstractParser<CustomBinaryBodyMetricProto>() {
    public CustomBinaryBodyMetricProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CustomBinaryBodyMetricProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CustomBinaryBodyMetricProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CustomBinaryBodyMetricProto> getParserForType() {
    return PARSER;
  }

  public org.corps.bi.metrics.protobuf.CustomBinaryBodyMetricProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

