// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package org.corps.bi.metrics.protobuf;

/**
 * Protobuf type {@code metrics.GameInfoProto}
 */
public  final class GameInfoProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:metrics.GameInfoProto)
    GameInfoProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GameInfoProto.newBuilder() to construct.
  private GameInfoProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameInfoProto() {
    clientId_ = "";
    userId_ = "";
    userLevel_ = "";
    gameinfo_ = "";
    value_ = "";
    kingdom_ = "";
    phylum_ = "";
    classfield_ = "";
    family_ = "";
    genus_ = "";
    gameinfoDate_ = "";
    gameinfoTime_ = "";
    extra_ = "";
    version_ = 0;
    udid_ = "";
    roleid_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GameInfoProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            clientId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            userLevel_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            gameinfo_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            value_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            kingdom_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            phylum_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            classfield_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            family_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            genus_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            gameinfoDate_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            gameinfoTime_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            extra_ = s;
            break;
          }
          case 128: {

            version_ = input.readInt32();
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            udid_ = s;
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            roleid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.corps.bi.metrics.protobuf.GameInfoProto.class, org.corps.bi.metrics.protobuf.GameInfoProto.Builder.class);
  }

  public static final int CLIENTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object clientId_;
  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 4;
  private volatile java.lang.Object userId_;
  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERLEVEL_FIELD_NUMBER = 5;
  private volatile java.lang.Object userLevel_;
  /**
   * <code>string userLevel = 5;</code>
   */
  public java.lang.String getUserLevel() {
    java.lang.Object ref = userLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userLevel_ = s;
      return s;
    }
  }
  /**
   * <code>string userLevel = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUserLevelBytes() {
    java.lang.Object ref = userLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAMEINFO_FIELD_NUMBER = 6;
  private volatile java.lang.Object gameinfo_;
  /**
   * <code>string gameinfo = 6;</code>
   */
  public java.lang.String getGameinfo() {
    java.lang.Object ref = gameinfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameinfo_ = s;
      return s;
    }
  }
  /**
   * <code>string gameinfo = 6;</code>
   */
  public com.google.protobuf.ByteString
      getGameinfoBytes() {
    java.lang.Object ref = gameinfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameinfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 7;
  private volatile java.lang.Object value_;
  /**
   * <code>string value = 7;</code>
   */
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <code>string value = 7;</code>
   */
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KINGDOM_FIELD_NUMBER = 8;
  private volatile java.lang.Object kingdom_;
  /**
   * <code>string kingdom = 8;</code>
   */
  public java.lang.String getKingdom() {
    java.lang.Object ref = kingdom_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kingdom_ = s;
      return s;
    }
  }
  /**
   * <code>string kingdom = 8;</code>
   */
  public com.google.protobuf.ByteString
      getKingdomBytes() {
    java.lang.Object ref = kingdom_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kingdom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHYLUM_FIELD_NUMBER = 9;
  private volatile java.lang.Object phylum_;
  /**
   * <code>string phylum = 9;</code>
   */
  public java.lang.String getPhylum() {
    java.lang.Object ref = phylum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phylum_ = s;
      return s;
    }
  }
  /**
   * <code>string phylum = 9;</code>
   */
  public com.google.protobuf.ByteString
      getPhylumBytes() {
    java.lang.Object ref = phylum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phylum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLASSFIELD_FIELD_NUMBER = 10;
  private volatile java.lang.Object classfield_;
  /**
   * <code>string classfield = 10;</code>
   */
  public java.lang.String getClassfield() {
    java.lang.Object ref = classfield_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      classfield_ = s;
      return s;
    }
  }
  /**
   * <code>string classfield = 10;</code>
   */
  public com.google.protobuf.ByteString
      getClassfieldBytes() {
    java.lang.Object ref = classfield_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      classfield_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAMILY_FIELD_NUMBER = 11;
  private volatile java.lang.Object family_;
  /**
   * <code>string family = 11;</code>
   */
  public java.lang.String getFamily() {
    java.lang.Object ref = family_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      family_ = s;
      return s;
    }
  }
  /**
   * <code>string family = 11;</code>
   */
  public com.google.protobuf.ByteString
      getFamilyBytes() {
    java.lang.Object ref = family_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      family_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENUS_FIELD_NUMBER = 12;
  private volatile java.lang.Object genus_;
  /**
   * <code>string genus = 12;</code>
   */
  public java.lang.String getGenus() {
    java.lang.Object ref = genus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      genus_ = s;
      return s;
    }
  }
  /**
   * <code>string genus = 12;</code>
   */
  public com.google.protobuf.ByteString
      getGenusBytes() {
    java.lang.Object ref = genus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAMEINFODATE_FIELD_NUMBER = 13;
  private volatile java.lang.Object gameinfoDate_;
  /**
   * <code>string gameinfoDate = 13;</code>
   */
  public java.lang.String getGameinfoDate() {
    java.lang.Object ref = gameinfoDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameinfoDate_ = s;
      return s;
    }
  }
  /**
   * <code>string gameinfoDate = 13;</code>
   */
  public com.google.protobuf.ByteString
      getGameinfoDateBytes() {
    java.lang.Object ref = gameinfoDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameinfoDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GAMEINFOTIME_FIELD_NUMBER = 14;
  private volatile java.lang.Object gameinfoTime_;
  /**
   * <code>string gameinfoTime = 14;</code>
   */
  public java.lang.String getGameinfoTime() {
    java.lang.Object ref = gameinfoTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gameinfoTime_ = s;
      return s;
    }
  }
  /**
   * <code>string gameinfoTime = 14;</code>
   */
  public com.google.protobuf.ByteString
      getGameinfoTimeBytes() {
    java.lang.Object ref = gameinfoTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameinfoTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRA_FIELD_NUMBER = 15;
  private volatile java.lang.Object extra_;
  /**
   * <code>string extra = 15;</code>
   */
  public java.lang.String getExtra() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extra_ = s;
      return s;
    }
  }
  /**
   * <code>string extra = 15;</code>
   */
  public com.google.protobuf.ByteString
      getExtraBytes() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 16;
  private int version_;
  /**
   * <code>int32 version = 16;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int UDID_FIELD_NUMBER = 17;
  private volatile java.lang.Object udid_;
  /**
   * <code>string udid = 17;</code>
   */
  public java.lang.String getUdid() {
    java.lang.Object ref = udid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      udid_ = s;
      return s;
    }
  }
  /**
   * <code>string udid = 17;</code>
   */
  public com.google.protobuf.ByteString
      getUdidBytes() {
    java.lang.Object ref = udid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      udid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLEID_FIELD_NUMBER = 18;
  private volatile java.lang.Object roleid_;
  /**
   * <code>string roleid = 18;</code>
   */
  public java.lang.String getRoleid() {
    java.lang.Object ref = roleid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roleid_ = s;
      return s;
    }
  }
  /**
   * <code>string roleid = 18;</code>
   */
  public com.google.protobuf.ByteString
      getRoleidBytes() {
    java.lang.Object ref = roleid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roleid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
    }
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userId_);
    }
    if (!getUserLevelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userLevel_);
    }
    if (!getGameinfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, gameinfo_);
    }
    if (!getValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, value_);
    }
    if (!getKingdomBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, kingdom_);
    }
    if (!getPhylumBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, phylum_);
    }
    if (!getClassfieldBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, classfield_);
    }
    if (!getFamilyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, family_);
    }
    if (!getGenusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, genus_);
    }
    if (!getGameinfoDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, gameinfoDate_);
    }
    if (!getGameinfoTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, gameinfoTime_);
    }
    if (!getExtraBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, extra_);
    }
    if (version_ != 0) {
      output.writeInt32(16, version_);
    }
    if (!getUdidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, udid_);
    }
    if (!getRoleidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, roleid_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
    }
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userId_);
    }
    if (!getUserLevelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userLevel_);
    }
    if (!getGameinfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, gameinfo_);
    }
    if (!getValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, value_);
    }
    if (!getKingdomBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, kingdom_);
    }
    if (!getPhylumBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, phylum_);
    }
    if (!getClassfieldBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, classfield_);
    }
    if (!getFamilyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, family_);
    }
    if (!getGenusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, genus_);
    }
    if (!getGameinfoDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, gameinfoDate_);
    }
    if (!getGameinfoTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, gameinfoTime_);
    }
    if (!getExtraBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, extra_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, version_);
    }
    if (!getUdidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, udid_);
    }
    if (!getRoleidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, roleid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.corps.bi.metrics.protobuf.GameInfoProto)) {
      return super.equals(obj);
    }
    org.corps.bi.metrics.protobuf.GameInfoProto other = (org.corps.bi.metrics.protobuf.GameInfoProto) obj;

    boolean result = true;
    result = result && getClientId()
        .equals(other.getClientId());
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && getUserLevel()
        .equals(other.getUserLevel());
    result = result && getGameinfo()
        .equals(other.getGameinfo());
    result = result && getValue()
        .equals(other.getValue());
    result = result && getKingdom()
        .equals(other.getKingdom());
    result = result && getPhylum()
        .equals(other.getPhylum());
    result = result && getClassfield()
        .equals(other.getClassfield());
    result = result && getFamily()
        .equals(other.getFamily());
    result = result && getGenus()
        .equals(other.getGenus());
    result = result && getGameinfoDate()
        .equals(other.getGameinfoDate());
    result = result && getGameinfoTime()
        .equals(other.getGameinfoTime());
    result = result && getExtra()
        .equals(other.getExtra());
    result = result && (getVersion()
        == other.getVersion());
    result = result && getUdid()
        .equals(other.getUdid());
    result = result && getRoleid()
        .equals(other.getRoleid());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + USERLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getUserLevel().hashCode();
    hash = (37 * hash) + GAMEINFO_FIELD_NUMBER;
    hash = (53 * hash) + getGameinfo().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (37 * hash) + KINGDOM_FIELD_NUMBER;
    hash = (53 * hash) + getKingdom().hashCode();
    hash = (37 * hash) + PHYLUM_FIELD_NUMBER;
    hash = (53 * hash) + getPhylum().hashCode();
    hash = (37 * hash) + CLASSFIELD_FIELD_NUMBER;
    hash = (53 * hash) + getClassfield().hashCode();
    hash = (37 * hash) + FAMILY_FIELD_NUMBER;
    hash = (53 * hash) + getFamily().hashCode();
    hash = (37 * hash) + GENUS_FIELD_NUMBER;
    hash = (53 * hash) + getGenus().hashCode();
    hash = (37 * hash) + GAMEINFODATE_FIELD_NUMBER;
    hash = (53 * hash) + getGameinfoDate().hashCode();
    hash = (37 * hash) + GAMEINFOTIME_FIELD_NUMBER;
    hash = (53 * hash) + getGameinfoTime().hashCode();
    hash = (37 * hash) + EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getExtra().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + UDID_FIELD_NUMBER;
    hash = (53 * hash) + getUdid().hashCode();
    hash = (37 * hash) + ROLEID_FIELD_NUMBER;
    hash = (53 * hash) + getRoleid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.corps.bi.metrics.protobuf.GameInfoProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code metrics.GameInfoProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:metrics.GameInfoProto)
      org.corps.bi.metrics.protobuf.GameInfoProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.corps.bi.metrics.protobuf.GameInfoProto.class, org.corps.bi.metrics.protobuf.GameInfoProto.Builder.class);
    }

    // Construct using org.corps.bi.metrics.protobuf.GameInfoProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      clientId_ = "";

      userId_ = "";

      userLevel_ = "";

      gameinfo_ = "";

      value_ = "";

      kingdom_ = "";

      phylum_ = "";

      classfield_ = "";

      family_ = "";

      genus_ = "";

      gameinfoDate_ = "";

      gameinfoTime_ = "";

      extra_ = "";

      version_ = 0;

      udid_ = "";

      roleid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_descriptor;
    }

    public org.corps.bi.metrics.protobuf.GameInfoProto getDefaultInstanceForType() {
      return org.corps.bi.metrics.protobuf.GameInfoProto.getDefaultInstance();
    }

    public org.corps.bi.metrics.protobuf.GameInfoProto build() {
      org.corps.bi.metrics.protobuf.GameInfoProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.corps.bi.metrics.protobuf.GameInfoProto buildPartial() {
      org.corps.bi.metrics.protobuf.GameInfoProto result = new org.corps.bi.metrics.protobuf.GameInfoProto(this);
      result.clientId_ = clientId_;
      result.userId_ = userId_;
      result.userLevel_ = userLevel_;
      result.gameinfo_ = gameinfo_;
      result.value_ = value_;
      result.kingdom_ = kingdom_;
      result.phylum_ = phylum_;
      result.classfield_ = classfield_;
      result.family_ = family_;
      result.genus_ = genus_;
      result.gameinfoDate_ = gameinfoDate_;
      result.gameinfoTime_ = gameinfoTime_;
      result.extra_ = extra_;
      result.version_ = version_;
      result.udid_ = udid_;
      result.roleid_ = roleid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.corps.bi.metrics.protobuf.GameInfoProto) {
        return mergeFrom((org.corps.bi.metrics.protobuf.GameInfoProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.corps.bi.metrics.protobuf.GameInfoProto other) {
      if (other == org.corps.bi.metrics.protobuf.GameInfoProto.getDefaultInstance()) return this;
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getUserLevel().isEmpty()) {
        userLevel_ = other.userLevel_;
        onChanged();
      }
      if (!other.getGameinfo().isEmpty()) {
        gameinfo_ = other.gameinfo_;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      if (!other.getKingdom().isEmpty()) {
        kingdom_ = other.kingdom_;
        onChanged();
      }
      if (!other.getPhylum().isEmpty()) {
        phylum_ = other.phylum_;
        onChanged();
      }
      if (!other.getClassfield().isEmpty()) {
        classfield_ = other.classfield_;
        onChanged();
      }
      if (!other.getFamily().isEmpty()) {
        family_ = other.family_;
        onChanged();
      }
      if (!other.getGenus().isEmpty()) {
        genus_ = other.genus_;
        onChanged();
      }
      if (!other.getGameinfoDate().isEmpty()) {
        gameinfoDate_ = other.gameinfoDate_;
        onChanged();
      }
      if (!other.getGameinfoTime().isEmpty()) {
        gameinfoTime_ = other.gameinfoTime_;
        onChanged();
      }
      if (!other.getExtra().isEmpty()) {
        extra_ = other.extra_;
        onChanged();
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (!other.getUdid().isEmpty()) {
        udid_ = other.udid_;
        onChanged();
      }
      if (!other.getRoleid().isEmpty()) {
        roleid_ = other.roleid_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.corps.bi.metrics.protobuf.GameInfoProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.corps.bi.metrics.protobuf.GameInfoProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clientId_ = "";
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public Builder clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string gameId = 1;
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *string ds = 3;
     * </pre>
     *
     * <code>string userId = 4;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userLevel_ = "";
    /**
     * <code>string userLevel = 5;</code>
     */
    public java.lang.String getUserLevel() {
      java.lang.Object ref = userLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userLevel = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserLevelBytes() {
      java.lang.Object ref = userLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userLevel = 5;</code>
     */
    public Builder setUserLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userLevel = 5;</code>
     */
    public Builder clearUserLevel() {
      
      userLevel_ = getDefaultInstance().getUserLevel();
      onChanged();
      return this;
    }
    /**
     * <code>string userLevel = 5;</code>
     */
    public Builder setUserLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userLevel_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gameinfo_ = "";
    /**
     * <code>string gameinfo = 6;</code>
     */
    public java.lang.String getGameinfo() {
      java.lang.Object ref = gameinfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameinfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gameinfo = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGameinfoBytes() {
      java.lang.Object ref = gameinfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameinfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gameinfo = 6;</code>
     */
    public Builder setGameinfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameinfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gameinfo = 6;</code>
     */
    public Builder clearGameinfo() {
      
      gameinfo_ = getDefaultInstance().getGameinfo();
      onChanged();
      return this;
    }
    /**
     * <code>string gameinfo = 6;</code>
     */
    public Builder setGameinfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gameinfo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <code>string value = 7;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string value = 7;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string value = 7;</code>
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string value = 7;</code>
     */
    public Builder clearValue() {
      
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <code>string value = 7;</code>
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object kingdom_ = "";
    /**
     * <code>string kingdom = 8;</code>
     */
    public java.lang.String getKingdom() {
      java.lang.Object ref = kingdom_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kingdom_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string kingdom = 8;</code>
     */
    public com.google.protobuf.ByteString
        getKingdomBytes() {
      java.lang.Object ref = kingdom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kingdom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string kingdom = 8;</code>
     */
    public Builder setKingdom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      kingdom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string kingdom = 8;</code>
     */
    public Builder clearKingdom() {
      
      kingdom_ = getDefaultInstance().getKingdom();
      onChanged();
      return this;
    }
    /**
     * <code>string kingdom = 8;</code>
     */
    public Builder setKingdomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      kingdom_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phylum_ = "";
    /**
     * <code>string phylum = 9;</code>
     */
    public java.lang.String getPhylum() {
      java.lang.Object ref = phylum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phylum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string phylum = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPhylumBytes() {
      java.lang.Object ref = phylum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phylum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string phylum = 9;</code>
     */
    public Builder setPhylum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      phylum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string phylum = 9;</code>
     */
    public Builder clearPhylum() {
      
      phylum_ = getDefaultInstance().getPhylum();
      onChanged();
      return this;
    }
    /**
     * <code>string phylum = 9;</code>
     */
    public Builder setPhylumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      phylum_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object classfield_ = "";
    /**
     * <code>string classfield = 10;</code>
     */
    public java.lang.String getClassfield() {
      java.lang.Object ref = classfield_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        classfield_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string classfield = 10;</code>
     */
    public com.google.protobuf.ByteString
        getClassfieldBytes() {
      java.lang.Object ref = classfield_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        classfield_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string classfield = 10;</code>
     */
    public Builder setClassfield(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      classfield_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string classfield = 10;</code>
     */
    public Builder clearClassfield() {
      
      classfield_ = getDefaultInstance().getClassfield();
      onChanged();
      return this;
    }
    /**
     * <code>string classfield = 10;</code>
     */
    public Builder setClassfieldBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      classfield_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object family_ = "";
    /**
     * <code>string family = 11;</code>
     */
    public java.lang.String getFamily() {
      java.lang.Object ref = family_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        family_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string family = 11;</code>
     */
    public com.google.protobuf.ByteString
        getFamilyBytes() {
      java.lang.Object ref = family_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        family_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string family = 11;</code>
     */
    public Builder setFamily(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      family_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string family = 11;</code>
     */
    public Builder clearFamily() {
      
      family_ = getDefaultInstance().getFamily();
      onChanged();
      return this;
    }
    /**
     * <code>string family = 11;</code>
     */
    public Builder setFamilyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      family_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object genus_ = "";
    /**
     * <code>string genus = 12;</code>
     */
    public java.lang.String getGenus() {
      java.lang.Object ref = genus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string genus = 12;</code>
     */
    public com.google.protobuf.ByteString
        getGenusBytes() {
      java.lang.Object ref = genus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string genus = 12;</code>
     */
    public Builder setGenus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      genus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string genus = 12;</code>
     */
    public Builder clearGenus() {
      
      genus_ = getDefaultInstance().getGenus();
      onChanged();
      return this;
    }
    /**
     * <code>string genus = 12;</code>
     */
    public Builder setGenusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      genus_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gameinfoDate_ = "";
    /**
     * <code>string gameinfoDate = 13;</code>
     */
    public java.lang.String getGameinfoDate() {
      java.lang.Object ref = gameinfoDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameinfoDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gameinfoDate = 13;</code>
     */
    public com.google.protobuf.ByteString
        getGameinfoDateBytes() {
      java.lang.Object ref = gameinfoDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameinfoDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gameinfoDate = 13;</code>
     */
    public Builder setGameinfoDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameinfoDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gameinfoDate = 13;</code>
     */
    public Builder clearGameinfoDate() {
      
      gameinfoDate_ = getDefaultInstance().getGameinfoDate();
      onChanged();
      return this;
    }
    /**
     * <code>string gameinfoDate = 13;</code>
     */
    public Builder setGameinfoDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gameinfoDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gameinfoTime_ = "";
    /**
     * <code>string gameinfoTime = 14;</code>
     */
    public java.lang.String getGameinfoTime() {
      java.lang.Object ref = gameinfoTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameinfoTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gameinfoTime = 14;</code>
     */
    public com.google.protobuf.ByteString
        getGameinfoTimeBytes() {
      java.lang.Object ref = gameinfoTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameinfoTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gameinfoTime = 14;</code>
     */
    public Builder setGameinfoTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gameinfoTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gameinfoTime = 14;</code>
     */
    public Builder clearGameinfoTime() {
      
      gameinfoTime_ = getDefaultInstance().getGameinfoTime();
      onChanged();
      return this;
    }
    /**
     * <code>string gameinfoTime = 14;</code>
     */
    public Builder setGameinfoTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gameinfoTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object extra_ = "";
    /**
     * <code>string extra = 15;</code>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extra = 15;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extra = 15;</code>
     */
    public Builder setExtra(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extra_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 15;</code>
     */
    public Builder clearExtra() {
      
      extra_ = getDefaultInstance().getExtra();
      onChanged();
      return this;
    }
    /**
     * <code>string extra = 15;</code>
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extra_ = value;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 16;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 16;</code>
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 16;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object udid_ = "";
    /**
     * <code>string udid = 17;</code>
     */
    public java.lang.String getUdid() {
      java.lang.Object ref = udid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        udid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string udid = 17;</code>
     */
    public com.google.protobuf.ByteString
        getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string udid = 17;</code>
     */
    public Builder setUdid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      udid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string udid = 17;</code>
     */
    public Builder clearUdid() {
      
      udid_ = getDefaultInstance().getUdid();
      onChanged();
      return this;
    }
    /**
     * <code>string udid = 17;</code>
     */
    public Builder setUdidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      udid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object roleid_ = "";
    /**
     * <code>string roleid = 18;</code>
     */
    public java.lang.String getRoleid() {
      java.lang.Object ref = roleid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roleid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string roleid = 18;</code>
     */
    public com.google.protobuf.ByteString
        getRoleidBytes() {
      java.lang.Object ref = roleid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string roleid = 18;</code>
     */
    public Builder setRoleid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roleid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string roleid = 18;</code>
     */
    public Builder clearRoleid() {
      
      roleid_ = getDefaultInstance().getRoleid();
      onChanged();
      return this;
    }
    /**
     * <code>string roleid = 18;</code>
     */
    public Builder setRoleidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roleid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:metrics.GameInfoProto)
  }

  // @@protoc_insertion_point(class_scope:metrics.GameInfoProto)
  private static final org.corps.bi.metrics.protobuf.GameInfoProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.corps.bi.metrics.protobuf.GameInfoProto();
  }

  public static org.corps.bi.metrics.protobuf.GameInfoProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameInfoProto>
      PARSER = new com.google.protobuf.AbstractParser<GameInfoProto>() {
    public GameInfoProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GameInfoProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GameInfoProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameInfoProto> getParserForType() {
    return PARSER;
  }

  public org.corps.bi.metrics.protobuf.GameInfoProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

