// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package org.corps.bi.metrics.protobuf;

public final class MetricsProto {
  private MetricsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_MetaProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_MetaProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_DauProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_DauProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_InstallProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_InstallProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_CounterProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_CounterProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_EconomyProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_EconomyProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_GameInfoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_GameInfoProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_MilestoneProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_MilestoneProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_PaymentProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_PaymentProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_AdTrackingProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_AdTrackingProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metrics_CustomBinaryBodyMetricProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metrics_CustomBinaryBodyMetricProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmetrics.proto\022\007metrics\"T\n\tMetaProto\022\016\n" +
      "\006metric\030\001 \001(\t\022\014\n\004snId\030\002 \001(\t\022\016\n\006gameId\030\003 " +
      "\001(\t\022\n\n\002ds\030\004 \001(\t\022\r\n\005extra\030\005 \001(\t\"\375\001\n\010DauPr" +
      "oto\022\020\n\010clientId\030\002 \001(\t\022\016\n\006userId\030\004 \001(\t\022\016\n" +
      "\006source\030\005 \001(\t\022\021\n\taffiliate\030\006 \001(\t\022\020\n\010crea" +
      "tive\030\007 \001(\t\022\016\n\006family\030\010 \001(\t\022\r\n\005genus\030\t \001(" +
      "\t\022\n\n\002ip\030\n \001(\t\022\017\n\007dauDate\030\013 \001(\t\022\017\n\007dauTim" +
      "e\030\014 \001(\t\022\017\n\007fromUid\030\r \001(\t\022\r\n\005extra\030\016 \001(\t\022" +
      "\017\n\007version\030\017 \001(\005\022\014\n\004udid\030\020 \001(\t\022\016\n\006roleid" +
      "\030\021 \001(\t\"\375\001\n\014InstallProto\022\020\n\010clientId\030\002 \001(" +
      "\t\022\016\n\006userId\030\004 \001(\t\022\016\n\006source\030\005 \001(\t\022\021\n\taff" +
      "iliate\030\006 \001(\t\022\020\n\010creative\030\007 \001(\t\022\016\n\006family" +
      "\030\010 \001(\t\022\r\n\005genus\030\t \001(\t\022\017\n\007fromUid\030\n \001(\t\022\023" +
      "\n\013installDate\030\013 \001(\t\022\023\n\013installTime\030\014 \001(\t" +
      "\022\r\n\005extra\030\r \001(\t\022\017\n\007version\030\016 \001(\005\022\014\n\004udid" +
      "\030\017 \001(\t\022\016\n\006roleid\030\020 \001(\t\"\237\002\n\014CounterProto\022" +
      "\020\n\010clientId\030\002 \001(\t\022\016\n\006userId\030\004 \001(\t\022\021\n\tuse" +
      "rLevel\030\005 \001(\t\022\017\n\007counter\030\006 \001(\t\022\r\n\005value\030\007" +
      " \001(\t\022\017\n\007kingdom\030\010 \001(\t\022\016\n\006phylum\030\t \001(\t\022\022\n" +
      "\nclassfield\030\n \001(\t\022\016\n\006family\030\013 \001(\t\022\r\n\005gen" +
      "us\030\014 \001(\t\022\023\n\013counterDate\030\r \001(\t\022\023\n\013counter" +
      "Time\030\016 \001(\t\022\r\n\005extra\030\017 \001(\t\022\017\n\007version\030\020 \001" +
      "(\005\022\014\n\004udid\030\021 \001(\t\022\016\n\006roleid\030\022 \001(\t\"\235\002\n\014Eco" +
      "nomyProto\022\020\n\010clientId\030\002 \001(\t\022\016\n\006userId\030\004 " +
      "\001(\t\022\020\n\010currency\030\005 \001(\t\022\016\n\006amount\030\006 \001(\t\022\r\n" +
      "\005value\030\007 \001(\t\022\017\n\007kingdom\030\010 \001(\t\022\016\n\006phylum\030" +
      "\t \001(\t\022\022\n\nclassfield\030\n \001(\t\022\016\n\006family\030\013 \001(" +
      "\t\022\r\n\005genus\030\014 \001(\t\022\023\n\013economyDate\030\r \001(\t\022\023\n" +
      "\013economyTime\030\016 \001(\t\022\r\n\005extra\030\017 \001(\t\022\017\n\007ver" +
      "sion\030\020 \001(\005\022\014\n\004udid\030\021 \001(\t\022\016\n\006roleid\030\022 \001(\t" +
      "\"\243\002\n\rGameInfoProto\022\020\n\010clientId\030\002 \001(\t\022\016\n\006" +
      "userId\030\004 \001(\t\022\021\n\tuserLevel\030\005 \001(\t\022\020\n\010gamei" +
      "nfo\030\006 \001(\t\022\r\n\005value\030\007 \001(\t\022\017\n\007kingdom\030\010 \001(" +
      "\t\022\016\n\006phylum\030\t \001(\t\022\022\n\nclassfield\030\n \001(\t\022\016\n" +
      "\006family\030\013 \001(\t\022\r\n\005genus\030\014 \001(\t\022\024\n\014gameinfo" +
      "Date\030\r \001(\t\022\024\n\014gameinfoTime\030\016 \001(\t\022\r\n\005extr" +
      "a\030\017 \001(\t\022\017\n\007version\030\020 \001(\005\022\014\n\004udid\030\021 \001(\t\022\016" +
      "\n\006roleid\030\022 \001(\t\"\300\001\n\016MilestoneProto\022\020\n\010cli" +
      "entId\030\002 \001(\t\022\016\n\006userId\030\004 \001(\t\022\021\n\tmilestone" +
      "\030\005 \001(\t\022\r\n\005value\030\006 \001(\t\022\025\n\rmilestoneDate\030\007" +
      " \001(\t\022\025\n\rmilestoneTime\030\010 \001(\t\022\r\n\005extra\030\t \001" +
      "(\t\022\017\n\007version\030\n \001(\005\022\014\n\004udid\030\013 \001(\t\022\016\n\006rol" +
      "eid\030\014 \001(\t\"\260\002\n\014PaymentProto\022\020\n\010clientId\030\002" +
      " \001(\t\022\016\n\006userId\030\004 \001(\t\022\016\n\006amount\030\005 \001(\t\022\020\n\010" +
      "currency\030\006 \001(\t\022\020\n\010provider\030\007 \001(\t\022\n\n\002ip\030\010" +
      " \001(\t\022\025\n\rtransactionid\030\t \001(\t\022\016\n\006status\030\n " +
      "\001(\t\022\017\n\007kingdom\030\013 \001(\t\022\016\n\006phylum\030\014 \001(\t\022\016\n\006" +
      "value2\030\r \001(\t\022\023\n\013paymentDate\030\016 \001(\t\022\023\n\013pay" +
      "mentTime\030\017 \001(\t\022\r\n\005extra\030\020 \001(\t\022\017\n\007version" +
      "\030\021 \001(\005\022\014\n\004udid\030\022 \001(\t\022\016\n\006roleid\030\023 \001(\t\"\252\002\n" +
      "\017AdTrackingProto\022\020\n\010clientId\030\002 \001(\t\022\016\n\006us" +
      "erId\030\004 \001(\t\022\016\n\006appkey\030\005 \001(\t\022\013\n\003mac\030\006 \001(\t\022" +
      "\016\n\006macMd5\030\007 \001(\t\022\013\n\003ifa\030\010 \001(\t\022\016\n\006ifaMd5\030\t" +
      " \001(\t\022\014\n\004uuid\030\n \001(\t\022\017\n\007actType\030\013 \001(\005\022\017\n\007a" +
      "ctTime\030\r \001(\t\022\n\n\002pf\030\016 \001(\t\022\n\n\002ip\030\017 \001(\t\022\021\n\t" +
      "userAgent\030\020 \001(\t\022\r\n\005extra\030\021 \001(\t\022\022\n\ntracki" +
      "ngDs\030\022 \001(\t\022\017\n\007version\030\023 \001(\005\022\014\n\004udid\030\024 \001(" +
      "\t\022\016\n\006roleid\030\025 \001(\t\"\315\001\n\033CustomBinaryBodyMe" +
      "tricProto\022\020\n\010clientId\030\002 \001(\t\022\016\n\006userId\030\004 " +
      "\001(\t\022\030\n\020customMetircName\030\005 \001(\t\022\022\n\nmetricD" +
      "ate\030\006 \001(\t\022\022\n\nmetricTime\030\007 \001(\t\022\014\n\004body\030\010 " +
      "\001(\014\022\r\n\005extra\030\t \001(\t\022\017\n\007version\030\n \001(\005\022\014\n\004u" +
      "did\030\013 \001(\t\022\016\n\006roleid\030\014 \001(\tB/\n\035org.corps.b" +
      "i.metrics.protobufB\014MetricsProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_metrics_MetaProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_metrics_MetaProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_MetaProto_descriptor,
        new java.lang.String[] { "Metric", "SnId", "GameId", "Ds", "Extra", });
    internal_static_metrics_DauProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_metrics_DauProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_DauProto_descriptor,
        new java.lang.String[] { "ClientId", "UserId", "Source", "Affiliate", "Creative", "Family", "Genus", "Ip", "DauDate", "DauTime", "FromUid", "Extra", "Version", "Udid", "Roleid", });
    internal_static_metrics_InstallProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_metrics_InstallProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_InstallProto_descriptor,
        new java.lang.String[] { "ClientId", "UserId", "Source", "Affiliate", "Creative", "Family", "Genus", "FromUid", "InstallDate", "InstallTime", "Extra", "Version", "Udid", "Roleid", });
    internal_static_metrics_CounterProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_metrics_CounterProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_CounterProto_descriptor,
        new java.lang.String[] { "ClientId", "UserId", "UserLevel", "Counter", "Value", "Kingdom", "Phylum", "Classfield", "Family", "Genus", "CounterDate", "CounterTime", "Extra", "Version", "Udid", "Roleid", });
    internal_static_metrics_EconomyProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_metrics_EconomyProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_EconomyProto_descriptor,
        new java.lang.String[] { "ClientId", "UserId", "Currency", "Amount", "Value", "Kingdom", "Phylum", "Classfield", "Family", "Genus", "EconomyDate", "EconomyTime", "Extra", "Version", "Udid", "Roleid", });
    internal_static_metrics_GameInfoProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_metrics_GameInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_GameInfoProto_descriptor,
        new java.lang.String[] { "ClientId", "UserId", "UserLevel", "Gameinfo", "Value", "Kingdom", "Phylum", "Classfield", "Family", "Genus", "GameinfoDate", "GameinfoTime", "Extra", "Version", "Udid", "Roleid", });
    internal_static_metrics_MilestoneProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_metrics_MilestoneProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_MilestoneProto_descriptor,
        new java.lang.String[] { "ClientId", "UserId", "Milestone", "Value", "MilestoneDate", "MilestoneTime", "Extra", "Version", "Udid", "Roleid", });
    internal_static_metrics_PaymentProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_metrics_PaymentProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_PaymentProto_descriptor,
        new java.lang.String[] { "ClientId", "UserId", "Amount", "Currency", "Provider", "Ip", "Transactionid", "Status", "Kingdom", "Phylum", "Value2", "PaymentDate", "PaymentTime", "Extra", "Version", "Udid", "Roleid", });
    internal_static_metrics_AdTrackingProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_metrics_AdTrackingProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_AdTrackingProto_descriptor,
        new java.lang.String[] { "ClientId", "UserId", "Appkey", "Mac", "MacMd5", "Ifa", "IfaMd5", "Uuid", "ActType", "ActTime", "Pf", "Ip", "UserAgent", "Extra", "TrackingDs", "Version", "Udid", "Roleid", });
    internal_static_metrics_CustomBinaryBodyMetricProto_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_metrics_CustomBinaryBodyMetricProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metrics_CustomBinaryBodyMetricProto_descriptor,
        new java.lang.String[] { "ClientId", "UserId", "CustomMetircName", "MetricDate", "MetricTime", "Body", "Extra", "Version", "Udid", "Roleid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
