// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package org.corps.bi.metrics.protobuf;

public interface PaymentProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metrics.PaymentProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  java.lang.String getClientId();
  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  java.lang.String getUserId();
  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   **
   * 支付的金额
   * </pre>
   *
   * <code>string amount = 5;</code>
   */
  java.lang.String getAmount();
  /**
   * <pre>
   **
   * 支付的金额
   * </pre>
   *
   * <code>string amount = 5;</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <pre>
   **
   * 支付的货币类型
   * </pre>
   *
   * <code>string currency = 6;</code>
   */
  java.lang.String getCurrency();
  /**
   * <pre>
   **
   * 支付的货币类型
   * </pre>
   *
   * <code>string currency = 6;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <pre>
   **
   * 交易平台
   * </pre>
   *
   * <code>string provider = 7;</code>
   */
  java.lang.String getProvider();
  /**
   * <pre>
   **
   * 交易平台
   * </pre>
   *
   * <code>string provider = 7;</code>
   */
  com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <pre>
   **
   * ip地址
   * </pre>
   *
   * <code>string ip = 8;</code>
   */
  java.lang.String getIp();
  /**
   * <pre>
   **
   * ip地址
   * </pre>
   *
   * <code>string ip = 8;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   **
   * 交易流水号
   * </pre>
   *
   * <code>string transactionid = 9;</code>
   */
  java.lang.String getTransactionid();
  /**
   * <pre>
   **
   * 交易流水号
   * </pre>
   *
   * <code>string transactionid = 9;</code>
   */
  com.google.protobuf.ByteString
      getTransactionidBytes();

  /**
   * <pre>
   **
   * 支付的状态
   * </pre>
   *
   * <code>string status = 10;</code>
   */
  java.lang.String getStatus();
  /**
   * <pre>
   **
   * 支付的状态
   * </pre>
   *
   * <code>string status = 10;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string kingdom = 11;</code>
   */
  java.lang.String getKingdom();
  /**
   * <code>string kingdom = 11;</code>
   */
  com.google.protobuf.ByteString
      getKingdomBytes();

  /**
   * <code>string phylum = 12;</code>
   */
  java.lang.String getPhylum();
  /**
   * <code>string phylum = 12;</code>
   */
  com.google.protobuf.ByteString
      getPhylumBytes();

  /**
   * <code>string value2 = 13;</code>
   */
  java.lang.String getValue2();
  /**
   * <code>string value2 = 13;</code>
   */
  com.google.protobuf.ByteString
      getValue2Bytes();

  /**
   * <code>string paymentDate = 14;</code>
   */
  java.lang.String getPaymentDate();
  /**
   * <code>string paymentDate = 14;</code>
   */
  com.google.protobuf.ByteString
      getPaymentDateBytes();

  /**
   * <code>string paymentTime = 15;</code>
   */
  java.lang.String getPaymentTime();
  /**
   * <code>string paymentTime = 15;</code>
   */
  com.google.protobuf.ByteString
      getPaymentTimeBytes();

  /**
   * <code>string extra = 16;</code>
   */
  java.lang.String getExtra();
  /**
   * <code>string extra = 16;</code>
   */
  com.google.protobuf.ByteString
      getExtraBytes();

  /**
   * <code>int32 version = 17;</code>
   */
  int getVersion();

  /**
   * <code>string udid = 18;</code>
   */
  java.lang.String getUdid();
  /**
   * <code>string udid = 18;</code>
   */
  com.google.protobuf.ByteString
      getUdidBytes();

  /**
   * <code>string roleid = 19;</code>
   */
  java.lang.String getRoleid();
  /**
   * <code>string roleid = 19;</code>
   */
  com.google.protobuf.ByteString
      getRoleidBytes();
}
