// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package org.corps.bi.metrics.protobuf;

public interface AdTrackingProtoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string clientId = 2;
  /**
   * <code>required string clientId = 2;</code>
   *
   * <pre>
   *required string gameId = 1;
   * </pre>
   */
  boolean hasClientId();
  /**
   * <code>required string clientId = 2;</code>
   *
   * <pre>
   *required string gameId = 1;
   * </pre>
   */
  java.lang.String getClientId();
  /**
   * <code>required string clientId = 2;</code>
   *
   * <pre>
   *required string gameId = 1;
   * </pre>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  // required string userId = 4;
  /**
   * <code>required string userId = 4;</code>
   *
   * <pre>
   *required string ds = 3;
   * </pre>
   */
  boolean hasUserId();
  /**
   * <code>required string userId = 4;</code>
   *
   * <pre>
   *required string ds = 3;
   * </pre>
   */
  java.lang.String getUserId();
  /**
   * <code>required string userId = 4;</code>
   *
   * <pre>
   *required string ds = 3;
   * </pre>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  // required string appkey = 5;
  /**
   * <code>required string appkey = 5;</code>
   */
  boolean hasAppkey();
  /**
   * <code>required string appkey = 5;</code>
   */
  java.lang.String getAppkey();
  /**
   * <code>required string appkey = 5;</code>
   */
  com.google.protobuf.ByteString
      getAppkeyBytes();

  // optional string mac = 6;
  /**
   * <code>optional string mac = 6;</code>
   */
  boolean hasMac();
  /**
   * <code>optional string mac = 6;</code>
   */
  java.lang.String getMac();
  /**
   * <code>optional string mac = 6;</code>
   */
  com.google.protobuf.ByteString
      getMacBytes();

  // optional string macMd5 = 7;
  /**
   * <code>optional string macMd5 = 7;</code>
   */
  boolean hasMacMd5();
  /**
   * <code>optional string macMd5 = 7;</code>
   */
  java.lang.String getMacMd5();
  /**
   * <code>optional string macMd5 = 7;</code>
   */
  com.google.protobuf.ByteString
      getMacMd5Bytes();

  // optional string ifa = 8;
  /**
   * <code>optional string ifa = 8;</code>
   */
  boolean hasIfa();
  /**
   * <code>optional string ifa = 8;</code>
   */
  java.lang.String getIfa();
  /**
   * <code>optional string ifa = 8;</code>
   */
  com.google.protobuf.ByteString
      getIfaBytes();

  // optional string ifaMd5 = 9;
  /**
   * <code>optional string ifaMd5 = 9;</code>
   */
  boolean hasIfaMd5();
  /**
   * <code>optional string ifaMd5 = 9;</code>
   */
  java.lang.String getIfaMd5();
  /**
   * <code>optional string ifaMd5 = 9;</code>
   */
  com.google.protobuf.ByteString
      getIfaMd5Bytes();

  // optional string uuid = 10;
  /**
   * <code>optional string uuid = 10;</code>
   */
  boolean hasUuid();
  /**
   * <code>optional string uuid = 10;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>optional string uuid = 10;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  // optional int32 actType = 11;
  /**
   * <code>optional int32 actType = 11;</code>
   *
   * <pre>
   **
   * 格式是：yyyy-MM-dd HH:mm:ss
   * </pre>
   */
  boolean hasActType();
  /**
   * <code>optional int32 actType = 11;</code>
   *
   * <pre>
   **
   * 格式是：yyyy-MM-dd HH:mm:ss
   * </pre>
   */
  int getActType();

  // required string actTime = 13;
  /**
   * <code>required string actTime = 13;</code>
   */
  boolean hasActTime();
  /**
   * <code>required string actTime = 13;</code>
   */
  java.lang.String getActTime();
  /**
   * <code>required string actTime = 13;</code>
   */
  com.google.protobuf.ByteString
      getActTimeBytes();

  // optional string pf = 14;
  /**
   * <code>optional string pf = 14;</code>
   */
  boolean hasPf();
  /**
   * <code>optional string pf = 14;</code>
   */
  java.lang.String getPf();
  /**
   * <code>optional string pf = 14;</code>
   */
  com.google.protobuf.ByteString
      getPfBytes();

  // optional string ip = 15;
  /**
   * <code>optional string ip = 15;</code>
   */
  boolean hasIp();
  /**
   * <code>optional string ip = 15;</code>
   */
  java.lang.String getIp();
  /**
   * <code>optional string ip = 15;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  // optional string userAgent = 16;
  /**
   * <code>optional string userAgent = 16;</code>
   */
  boolean hasUserAgent();
  /**
   * <code>optional string userAgent = 16;</code>
   */
  java.lang.String getUserAgent();
  /**
   * <code>optional string userAgent = 16;</code>
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  // optional string extra = 17;
  /**
   * <code>optional string extra = 17;</code>
   */
  boolean hasExtra();
  /**
   * <code>optional string extra = 17;</code>
   */
  java.lang.String getExtra();
  /**
   * <code>optional string extra = 17;</code>
   */
  com.google.protobuf.ByteString
      getExtraBytes();

  // optional string trackingDs = 18;
  /**
   * <code>optional string trackingDs = 18;</code>
   */
  boolean hasTrackingDs();
  /**
   * <code>optional string trackingDs = 18;</code>
   */
  java.lang.String getTrackingDs();
  /**
   * <code>optional string trackingDs = 18;</code>
   */
  com.google.protobuf.ByteString
      getTrackingDsBytes();

  // optional int32 version = 19;
  /**
   * <code>optional int32 version = 19;</code>
   */
  boolean hasVersion();
  /**
   * <code>optional int32 version = 19;</code>
   */
  int getVersion();

  // optional string udid = 20;
  /**
   * <code>optional string udid = 20;</code>
   */
  boolean hasUdid();
  /**
   * <code>optional string udid = 20;</code>
   */
  java.lang.String getUdid();
  /**
   * <code>optional string udid = 20;</code>
   */
  com.google.protobuf.ByteString
      getUdidBytes();

  // optional string roleid = 21;
  /**
   * <code>optional string roleid = 21;</code>
   */
  boolean hasRoleid();
  /**
   * <code>optional string roleid = 21;</code>
   */
  java.lang.String getRoleid();
  /**
   * <code>optional string roleid = 21;</code>
   */
  com.google.protobuf.ByteString
      getRoleidBytes();
}
