// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package org.corps.bi.metrics.protobuf;

/**
 * Protobuf type {@code metrics.GameInfoProto}
 */
public  final class GameInfoProto extends
    com.google.protobuf.GeneratedMessage
    implements GameInfoProtoOrBuilder {
  // Use GameInfoProto.newBuilder() to construct.
  private GameInfoProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private GameInfoProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final GameInfoProto defaultInstance;
  public static GameInfoProto getDefaultInstance() {
    return defaultInstance;
  }

  public GameInfoProto getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private GameInfoProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            bitField0_ |= 0x00000001;
            clientId_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000002;
            userId_ = input.readBytes();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000004;
            userLevel_ = input.readBytes();
            break;
          }
          case 50: {
            bitField0_ |= 0x00000008;
            gameinfo_ = input.readBytes();
            break;
          }
          case 58: {
            bitField0_ |= 0x00000010;
            value_ = input.readBytes();
            break;
          }
          case 66: {
            bitField0_ |= 0x00000020;
            kingdom_ = input.readBytes();
            break;
          }
          case 74: {
            bitField0_ |= 0x00000040;
            phylum_ = input.readBytes();
            break;
          }
          case 82: {
            bitField0_ |= 0x00000080;
            classfield_ = input.readBytes();
            break;
          }
          case 90: {
            bitField0_ |= 0x00000100;
            family_ = input.readBytes();
            break;
          }
          case 98: {
            bitField0_ |= 0x00000200;
            genus_ = input.readBytes();
            break;
          }
          case 106: {
            bitField0_ |= 0x00000400;
            gameinfoDate_ = input.readBytes();
            break;
          }
          case 114: {
            bitField0_ |= 0x00000800;
            gameinfoTime_ = input.readBytes();
            break;
          }
          case 122: {
            bitField0_ |= 0x00001000;
            extra_ = input.readBytes();
            break;
          }
          case 128: {
            bitField0_ |= 0x00002000;
            version_ = input.readInt32();
            break;
          }
          case 138: {
            bitField0_ |= 0x00004000;
            udid_ = input.readBytes();
            break;
          }
          case 146: {
            bitField0_ |= 0x00008000;
            roleid_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.corps.bi.metrics.protobuf.GameInfoProto.class, org.corps.bi.metrics.protobuf.GameInfoProto.Builder.class);
  }

  public static com.google.protobuf.Parser<GameInfoProto> PARSER =
      new com.google.protobuf.AbstractParser<GameInfoProto>() {
    public GameInfoProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GameInfoProto(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<GameInfoProto> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required string clientId = 2;
  public static final int CLIENTID_FIELD_NUMBER = 2;
  private java.lang.Object clientId_;
  /**
   * <code>required string clientId = 2;</code>
   *
   * <pre>
   *required string gameId = 1;
   * </pre>
   */
  public boolean hasClientId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string clientId = 2;</code>
   *
   * <pre>
   *required string gameId = 1;
   * </pre>
   */
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        clientId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string clientId = 2;</code>
   *
   * <pre>
   *required string gameId = 1;
   * </pre>
   */
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required string userId = 4;
  public static final int USERID_FIELD_NUMBER = 4;
  private java.lang.Object userId_;
  /**
   * <code>required string userId = 4;</code>
   *
   * <pre>
   *required string ds = 3;
   * </pre>
   */
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string userId = 4;</code>
   *
   * <pre>
   *required string ds = 3;
   * </pre>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string userId = 4;</code>
   *
   * <pre>
   *required string ds = 3;
   * </pre>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string userLevel = 5;
  public static final int USERLEVEL_FIELD_NUMBER = 5;
  private java.lang.Object userLevel_;
  /**
   * <code>optional string userLevel = 5;</code>
   */
  public boolean hasUserLevel() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string userLevel = 5;</code>
   */
  public java.lang.String getUserLevel() {
    java.lang.Object ref = userLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userLevel_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string userLevel = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUserLevelBytes() {
    java.lang.Object ref = userLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string gameinfo = 6;
  public static final int GAMEINFO_FIELD_NUMBER = 6;
  private java.lang.Object gameinfo_;
  /**
   * <code>optional string gameinfo = 6;</code>
   */
  public boolean hasGameinfo() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string gameinfo = 6;</code>
   */
  public java.lang.String getGameinfo() {
    java.lang.Object ref = gameinfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        gameinfo_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string gameinfo = 6;</code>
   */
  public com.google.protobuf.ByteString
      getGameinfoBytes() {
    java.lang.Object ref = gameinfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameinfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string value = 7;
  public static final int VALUE_FIELD_NUMBER = 7;
  private java.lang.Object value_;
  /**
   * <code>optional string value = 7;</code>
   */
  public boolean hasValue() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string value = 7;</code>
   */
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        value_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string value = 7;</code>
   */
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string kingdom = 8;
  public static final int KINGDOM_FIELD_NUMBER = 8;
  private java.lang.Object kingdom_;
  /**
   * <code>optional string kingdom = 8;</code>
   */
  public boolean hasKingdom() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string kingdom = 8;</code>
   */
  public java.lang.String getKingdom() {
    java.lang.Object ref = kingdom_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        kingdom_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string kingdom = 8;</code>
   */
  public com.google.protobuf.ByteString
      getKingdomBytes() {
    java.lang.Object ref = kingdom_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kingdom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string phylum = 9;
  public static final int PHYLUM_FIELD_NUMBER = 9;
  private java.lang.Object phylum_;
  /**
   * <code>optional string phylum = 9;</code>
   */
  public boolean hasPhylum() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional string phylum = 9;</code>
   */
  public java.lang.String getPhylum() {
    java.lang.Object ref = phylum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        phylum_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string phylum = 9;</code>
   */
  public com.google.protobuf.ByteString
      getPhylumBytes() {
    java.lang.Object ref = phylum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phylum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string classfield = 10;
  public static final int CLASSFIELD_FIELD_NUMBER = 10;
  private java.lang.Object classfield_;
  /**
   * <code>optional string classfield = 10;</code>
   */
  public boolean hasClassfield() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional string classfield = 10;</code>
   */
  public java.lang.String getClassfield() {
    java.lang.Object ref = classfield_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        classfield_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string classfield = 10;</code>
   */
  public com.google.protobuf.ByteString
      getClassfieldBytes() {
    java.lang.Object ref = classfield_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      classfield_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string family = 11;
  public static final int FAMILY_FIELD_NUMBER = 11;
  private java.lang.Object family_;
  /**
   * <code>optional string family = 11;</code>
   */
  public boolean hasFamily() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string family = 11;</code>
   */
  public java.lang.String getFamily() {
    java.lang.Object ref = family_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        family_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string family = 11;</code>
   */
  public com.google.protobuf.ByteString
      getFamilyBytes() {
    java.lang.Object ref = family_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      family_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string genus = 12;
  public static final int GENUS_FIELD_NUMBER = 12;
  private java.lang.Object genus_;
  /**
   * <code>optional string genus = 12;</code>
   */
  public boolean hasGenus() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional string genus = 12;</code>
   */
  public java.lang.String getGenus() {
    java.lang.Object ref = genus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        genus_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string genus = 12;</code>
   */
  public com.google.protobuf.ByteString
      getGenusBytes() {
    java.lang.Object ref = genus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required string gameinfoDate = 13;
  public static final int GAMEINFODATE_FIELD_NUMBER = 13;
  private java.lang.Object gameinfoDate_;
  /**
   * <code>required string gameinfoDate = 13;</code>
   */
  public boolean hasGameinfoDate() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <code>required string gameinfoDate = 13;</code>
   */
  public java.lang.String getGameinfoDate() {
    java.lang.Object ref = gameinfoDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        gameinfoDate_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string gameinfoDate = 13;</code>
   */
  public com.google.protobuf.ByteString
      getGameinfoDateBytes() {
    java.lang.Object ref = gameinfoDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameinfoDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required string gameinfoTime = 14;
  public static final int GAMEINFOTIME_FIELD_NUMBER = 14;
  private java.lang.Object gameinfoTime_;
  /**
   * <code>required string gameinfoTime = 14;</code>
   */
  public boolean hasGameinfoTime() {
    return ((bitField0_ & 0x00000800) == 0x00000800);
  }
  /**
   * <code>required string gameinfoTime = 14;</code>
   */
  public java.lang.String getGameinfoTime() {
    java.lang.Object ref = gameinfoTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        gameinfoTime_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string gameinfoTime = 14;</code>
   */
  public com.google.protobuf.ByteString
      getGameinfoTimeBytes() {
    java.lang.Object ref = gameinfoTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameinfoTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string extra = 15;
  public static final int EXTRA_FIELD_NUMBER = 15;
  private java.lang.Object extra_;
  /**
   * <code>optional string extra = 15;</code>
   */
  public boolean hasExtra() {
    return ((bitField0_ & 0x00001000) == 0x00001000);
  }
  /**
   * <code>optional string extra = 15;</code>
   */
  public java.lang.String getExtra() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        extra_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string extra = 15;</code>
   */
  public com.google.protobuf.ByteString
      getExtraBytes() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 version = 16;
  public static final int VERSION_FIELD_NUMBER = 16;
  private int version_;
  /**
   * <code>optional int32 version = 16;</code>
   */
  public boolean hasVersion() {
    return ((bitField0_ & 0x00002000) == 0x00002000);
  }
  /**
   * <code>optional int32 version = 16;</code>
   */
  public int getVersion() {
    return version_;
  }

  // optional string udid = 17;
  public static final int UDID_FIELD_NUMBER = 17;
  private java.lang.Object udid_;
  /**
   * <code>optional string udid = 17;</code>
   */
  public boolean hasUdid() {
    return ((bitField0_ & 0x00004000) == 0x00004000);
  }
  /**
   * <code>optional string udid = 17;</code>
   */
  public java.lang.String getUdid() {
    java.lang.Object ref = udid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        udid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string udid = 17;</code>
   */
  public com.google.protobuf.ByteString
      getUdidBytes() {
    java.lang.Object ref = udid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      udid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string roleid = 18;
  public static final int ROLEID_FIELD_NUMBER = 18;
  private java.lang.Object roleid_;
  /**
   * <code>optional string roleid = 18;</code>
   */
  public boolean hasRoleid() {
    return ((bitField0_ & 0x00008000) == 0x00008000);
  }
  /**
   * <code>optional string roleid = 18;</code>
   */
  public java.lang.String getRoleid() {
    java.lang.Object ref = roleid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        roleid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string roleid = 18;</code>
   */
  public com.google.protobuf.ByteString
      getRoleidBytes() {
    java.lang.Object ref = roleid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roleid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    clientId_ = "";
    userId_ = "";
    userLevel_ = "";
    gameinfo_ = "";
    value_ = "";
    kingdom_ = "";
    phylum_ = "";
    classfield_ = "";
    family_ = "";
    genus_ = "";
    gameinfoDate_ = "";
    gameinfoTime_ = "";
    extra_ = "";
    version_ = 0;
    udid_ = "";
    roleid_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasClientId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasUserId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasGameinfoDate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasGameinfoTime()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(2, getClientIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(4, getUserIdBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(5, getUserLevelBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(6, getGameinfoBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(7, getValueBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(8, getKingdomBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeBytes(9, getPhylumBytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeBytes(10, getClassfieldBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBytes(11, getFamilyBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBytes(12, getGenusBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeBytes(13, getGameinfoDateBytes());
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      output.writeBytes(14, getGameinfoTimeBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      output.writeBytes(15, getExtraBytes());
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      output.writeInt32(16, version_);
    }
    if (((bitField0_ & 0x00004000) == 0x00004000)) {
      output.writeBytes(17, getUdidBytes());
    }
    if (((bitField0_ & 0x00008000) == 0x00008000)) {
      output.writeBytes(18, getRoleidBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getClientIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getUserIdBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getUserLevelBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, getGameinfoBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, getValueBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, getKingdomBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, getPhylumBytes());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, getClassfieldBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(11, getFamilyBytes());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(12, getGenusBytes());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(13, getGameinfoDateBytes());
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(14, getGameinfoTimeBytes());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(15, getExtraBytes());
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, version_);
    }
    if (((bitField0_ & 0x00004000) == 0x00004000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(17, getUdidBytes());
    }
    if (((bitField0_ & 0x00008000) == 0x00008000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(18, getRoleidBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.corps.bi.metrics.protobuf.GameInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.corps.bi.metrics.protobuf.GameInfoProto prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code metrics.GameInfoProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements org.corps.bi.metrics.protobuf.GameInfoProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.corps.bi.metrics.protobuf.GameInfoProto.class, org.corps.bi.metrics.protobuf.GameInfoProto.Builder.class);
    }

    // Construct using org.corps.bi.metrics.protobuf.GameInfoProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      clientId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      userLevel_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      gameinfo_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      value_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      kingdom_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      phylum_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      classfield_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      family_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      genus_ = "";
      bitField0_ = (bitField0_ & ~0x00000200);
      gameinfoDate_ = "";
      bitField0_ = (bitField0_ & ~0x00000400);
      gameinfoTime_ = "";
      bitField0_ = (bitField0_ & ~0x00000800);
      extra_ = "";
      bitField0_ = (bitField0_ & ~0x00001000);
      version_ = 0;
      bitField0_ = (bitField0_ & ~0x00002000);
      udid_ = "";
      bitField0_ = (bitField0_ & ~0x00004000);
      roleid_ = "";
      bitField0_ = (bitField0_ & ~0x00008000);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.corps.bi.metrics.protobuf.MetricsProto.internal_static_metrics_GameInfoProto_descriptor;
    }

    public org.corps.bi.metrics.protobuf.GameInfoProto getDefaultInstanceForType() {
      return org.corps.bi.metrics.protobuf.GameInfoProto.getDefaultInstance();
    }

    public org.corps.bi.metrics.protobuf.GameInfoProto build() {
      org.corps.bi.metrics.protobuf.GameInfoProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.corps.bi.metrics.protobuf.GameInfoProto buildPartial() {
      org.corps.bi.metrics.protobuf.GameInfoProto result = new org.corps.bi.metrics.protobuf.GameInfoProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.clientId_ = clientId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.userId_ = userId_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.userLevel_ = userLevel_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.gameinfo_ = gameinfo_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.value_ = value_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.kingdom_ = kingdom_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.phylum_ = phylum_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.classfield_ = classfield_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.family_ = family_;
      if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
        to_bitField0_ |= 0x00000200;
      }
      result.genus_ = genus_;
      if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
        to_bitField0_ |= 0x00000400;
      }
      result.gameinfoDate_ = gameinfoDate_;
      if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
        to_bitField0_ |= 0x00000800;
      }
      result.gameinfoTime_ = gameinfoTime_;
      if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
        to_bitField0_ |= 0x00001000;
      }
      result.extra_ = extra_;
      if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
        to_bitField0_ |= 0x00002000;
      }
      result.version_ = version_;
      if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
        to_bitField0_ |= 0x00004000;
      }
      result.udid_ = udid_;
      if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
        to_bitField0_ |= 0x00008000;
      }
      result.roleid_ = roleid_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.corps.bi.metrics.protobuf.GameInfoProto) {
        return mergeFrom((org.corps.bi.metrics.protobuf.GameInfoProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.corps.bi.metrics.protobuf.GameInfoProto other) {
      if (other == org.corps.bi.metrics.protobuf.GameInfoProto.getDefaultInstance()) return this;
      if (other.hasClientId()) {
        bitField0_ |= 0x00000001;
        clientId_ = other.clientId_;
        onChanged();
      }
      if (other.hasUserId()) {
        bitField0_ |= 0x00000002;
        userId_ = other.userId_;
        onChanged();
      }
      if (other.hasUserLevel()) {
        bitField0_ |= 0x00000004;
        userLevel_ = other.userLevel_;
        onChanged();
      }
      if (other.hasGameinfo()) {
        bitField0_ |= 0x00000008;
        gameinfo_ = other.gameinfo_;
        onChanged();
      }
      if (other.hasValue()) {
        bitField0_ |= 0x00000010;
        value_ = other.value_;
        onChanged();
      }
      if (other.hasKingdom()) {
        bitField0_ |= 0x00000020;
        kingdom_ = other.kingdom_;
        onChanged();
      }
      if (other.hasPhylum()) {
        bitField0_ |= 0x00000040;
        phylum_ = other.phylum_;
        onChanged();
      }
      if (other.hasClassfield()) {
        bitField0_ |= 0x00000080;
        classfield_ = other.classfield_;
        onChanged();
      }
      if (other.hasFamily()) {
        bitField0_ |= 0x00000100;
        family_ = other.family_;
        onChanged();
      }
      if (other.hasGenus()) {
        bitField0_ |= 0x00000200;
        genus_ = other.genus_;
        onChanged();
      }
      if (other.hasGameinfoDate()) {
        bitField0_ |= 0x00000400;
        gameinfoDate_ = other.gameinfoDate_;
        onChanged();
      }
      if (other.hasGameinfoTime()) {
        bitField0_ |= 0x00000800;
        gameinfoTime_ = other.gameinfoTime_;
        onChanged();
      }
      if (other.hasExtra()) {
        bitField0_ |= 0x00001000;
        extra_ = other.extra_;
        onChanged();
      }
      if (other.hasVersion()) {
        setVersion(other.getVersion());
      }
      if (other.hasUdid()) {
        bitField0_ |= 0x00004000;
        udid_ = other.udid_;
        onChanged();
      }
      if (other.hasRoleid()) {
        bitField0_ |= 0x00008000;
        roleid_ = other.roleid_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasClientId()) {
        
        return false;
      }
      if (!hasUserId()) {
        
        return false;
      }
      if (!hasGameinfoDate()) {
        
        return false;
      }
      if (!hasGameinfoTime()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.corps.bi.metrics.protobuf.GameInfoProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.corps.bi.metrics.protobuf.GameInfoProto) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string clientId = 2;
    private java.lang.Object clientId_ = "";
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     *required string gameId = 1;
     * </pre>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     *required string gameId = 1;
     * </pre>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     *required string gameId = 1;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     *required string gameId = 1;
     * </pre>
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     *required string gameId = 1;
     * </pre>
     */
    public Builder clearClientId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      clientId_ = getDefaultInstance().getClientId();
      onChanged();
      return this;
    }
    /**
     * <code>required string clientId = 2;</code>
     *
     * <pre>
     *required string gameId = 1;
     * </pre>
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      clientId_ = value;
      onChanged();
      return this;
    }

    // required string userId = 4;
    private java.lang.Object userId_ = "";
    /**
     * <code>required string userId = 4;</code>
     *
     * <pre>
     *required string ds = 3;
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userId = 4;</code>
     *
     * <pre>
     *required string ds = 3;
     * </pre>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string userId = 4;</code>
     *
     * <pre>
     *required string ds = 3;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string userId = 4;</code>
     *
     * <pre>
     *required string ds = 3;
     * </pre>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string userId = 4;</code>
     *
     * <pre>
     *required string ds = 3;
     * </pre>
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>required string userId = 4;</code>
     *
     * <pre>
     *required string ds = 3;
     * </pre>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      userId_ = value;
      onChanged();
      return this;
    }

    // optional string userLevel = 5;
    private java.lang.Object userLevel_ = "";
    /**
     * <code>optional string userLevel = 5;</code>
     */
    public boolean hasUserLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string userLevel = 5;</code>
     */
    public java.lang.String getUserLevel() {
      java.lang.Object ref = userLevel_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        userLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string userLevel = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserLevelBytes() {
      java.lang.Object ref = userLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userLevel = 5;</code>
     */
    public Builder setUserLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      userLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userLevel = 5;</code>
     */
    public Builder clearUserLevel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userLevel_ = getDefaultInstance().getUserLevel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string userLevel = 5;</code>
     */
    public Builder setUserLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      userLevel_ = value;
      onChanged();
      return this;
    }

    // optional string gameinfo = 6;
    private java.lang.Object gameinfo_ = "";
    /**
     * <code>optional string gameinfo = 6;</code>
     */
    public boolean hasGameinfo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string gameinfo = 6;</code>
     */
    public java.lang.String getGameinfo() {
      java.lang.Object ref = gameinfo_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        gameinfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string gameinfo = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGameinfoBytes() {
      java.lang.Object ref = gameinfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameinfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string gameinfo = 6;</code>
     */
    public Builder setGameinfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      gameinfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string gameinfo = 6;</code>
     */
    public Builder clearGameinfo() {
      bitField0_ = (bitField0_ & ~0x00000008);
      gameinfo_ = getDefaultInstance().getGameinfo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string gameinfo = 6;</code>
     */
    public Builder setGameinfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      gameinfo_ = value;
      onChanged();
      return this;
    }

    // optional string value = 7;
    private java.lang.Object value_ = "";
    /**
     * <code>optional string value = 7;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string value = 7;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string value = 7;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string value = 7;</code>
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string value = 7;</code>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <code>optional string value = 7;</code>
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      value_ = value;
      onChanged();
      return this;
    }

    // optional string kingdom = 8;
    private java.lang.Object kingdom_ = "";
    /**
     * <code>optional string kingdom = 8;</code>
     */
    public boolean hasKingdom() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string kingdom = 8;</code>
     */
    public java.lang.String getKingdom() {
      java.lang.Object ref = kingdom_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        kingdom_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string kingdom = 8;</code>
     */
    public com.google.protobuf.ByteString
        getKingdomBytes() {
      java.lang.Object ref = kingdom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kingdom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string kingdom = 8;</code>
     */
    public Builder setKingdom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      kingdom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string kingdom = 8;</code>
     */
    public Builder clearKingdom() {
      bitField0_ = (bitField0_ & ~0x00000020);
      kingdom_ = getDefaultInstance().getKingdom();
      onChanged();
      return this;
    }
    /**
     * <code>optional string kingdom = 8;</code>
     */
    public Builder setKingdomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      kingdom_ = value;
      onChanged();
      return this;
    }

    // optional string phylum = 9;
    private java.lang.Object phylum_ = "";
    /**
     * <code>optional string phylum = 9;</code>
     */
    public boolean hasPhylum() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string phylum = 9;</code>
     */
    public java.lang.String getPhylum() {
      java.lang.Object ref = phylum_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        phylum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string phylum = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPhylumBytes() {
      java.lang.Object ref = phylum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phylum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string phylum = 9;</code>
     */
    public Builder setPhylum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      phylum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string phylum = 9;</code>
     */
    public Builder clearPhylum() {
      bitField0_ = (bitField0_ & ~0x00000040);
      phylum_ = getDefaultInstance().getPhylum();
      onChanged();
      return this;
    }
    /**
     * <code>optional string phylum = 9;</code>
     */
    public Builder setPhylumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      phylum_ = value;
      onChanged();
      return this;
    }

    // optional string classfield = 10;
    private java.lang.Object classfield_ = "";
    /**
     * <code>optional string classfield = 10;</code>
     */
    public boolean hasClassfield() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string classfield = 10;</code>
     */
    public java.lang.String getClassfield() {
      java.lang.Object ref = classfield_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        classfield_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string classfield = 10;</code>
     */
    public com.google.protobuf.ByteString
        getClassfieldBytes() {
      java.lang.Object ref = classfield_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        classfield_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string classfield = 10;</code>
     */
    public Builder setClassfield(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      classfield_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string classfield = 10;</code>
     */
    public Builder clearClassfield() {
      bitField0_ = (bitField0_ & ~0x00000080);
      classfield_ = getDefaultInstance().getClassfield();
      onChanged();
      return this;
    }
    /**
     * <code>optional string classfield = 10;</code>
     */
    public Builder setClassfieldBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      classfield_ = value;
      onChanged();
      return this;
    }

    // optional string family = 11;
    private java.lang.Object family_ = "";
    /**
     * <code>optional string family = 11;</code>
     */
    public boolean hasFamily() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string family = 11;</code>
     */
    public java.lang.String getFamily() {
      java.lang.Object ref = family_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        family_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string family = 11;</code>
     */
    public com.google.protobuf.ByteString
        getFamilyBytes() {
      java.lang.Object ref = family_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        family_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string family = 11;</code>
     */
    public Builder setFamily(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      family_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string family = 11;</code>
     */
    public Builder clearFamily() {
      bitField0_ = (bitField0_ & ~0x00000100);
      family_ = getDefaultInstance().getFamily();
      onChanged();
      return this;
    }
    /**
     * <code>optional string family = 11;</code>
     */
    public Builder setFamilyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      family_ = value;
      onChanged();
      return this;
    }

    // optional string genus = 12;
    private java.lang.Object genus_ = "";
    /**
     * <code>optional string genus = 12;</code>
     */
    public boolean hasGenus() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string genus = 12;</code>
     */
    public java.lang.String getGenus() {
      java.lang.Object ref = genus_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        genus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string genus = 12;</code>
     */
    public com.google.protobuf.ByteString
        getGenusBytes() {
      java.lang.Object ref = genus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string genus = 12;</code>
     */
    public Builder setGenus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      genus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string genus = 12;</code>
     */
    public Builder clearGenus() {
      bitField0_ = (bitField0_ & ~0x00000200);
      genus_ = getDefaultInstance().getGenus();
      onChanged();
      return this;
    }
    /**
     * <code>optional string genus = 12;</code>
     */
    public Builder setGenusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
      genus_ = value;
      onChanged();
      return this;
    }

    // required string gameinfoDate = 13;
    private java.lang.Object gameinfoDate_ = "";
    /**
     * <code>required string gameinfoDate = 13;</code>
     */
    public boolean hasGameinfoDate() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string gameinfoDate = 13;</code>
     */
    public java.lang.String getGameinfoDate() {
      java.lang.Object ref = gameinfoDate_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        gameinfoDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string gameinfoDate = 13;</code>
     */
    public com.google.protobuf.ByteString
        getGameinfoDateBytes() {
      java.lang.Object ref = gameinfoDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameinfoDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string gameinfoDate = 13;</code>
     */
    public Builder setGameinfoDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      gameinfoDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string gameinfoDate = 13;</code>
     */
    public Builder clearGameinfoDate() {
      bitField0_ = (bitField0_ & ~0x00000400);
      gameinfoDate_ = getDefaultInstance().getGameinfoDate();
      onChanged();
      return this;
    }
    /**
     * <code>required string gameinfoDate = 13;</code>
     */
    public Builder setGameinfoDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      gameinfoDate_ = value;
      onChanged();
      return this;
    }

    // required string gameinfoTime = 14;
    private java.lang.Object gameinfoTime_ = "";
    /**
     * <code>required string gameinfoTime = 14;</code>
     */
    public boolean hasGameinfoTime() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required string gameinfoTime = 14;</code>
     */
    public java.lang.String getGameinfoTime() {
      java.lang.Object ref = gameinfoTime_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        gameinfoTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string gameinfoTime = 14;</code>
     */
    public com.google.protobuf.ByteString
        getGameinfoTimeBytes() {
      java.lang.Object ref = gameinfoTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameinfoTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string gameinfoTime = 14;</code>
     */
    public Builder setGameinfoTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      gameinfoTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string gameinfoTime = 14;</code>
     */
    public Builder clearGameinfoTime() {
      bitField0_ = (bitField0_ & ~0x00000800);
      gameinfoTime_ = getDefaultInstance().getGameinfoTime();
      onChanged();
      return this;
    }
    /**
     * <code>required string gameinfoTime = 14;</code>
     */
    public Builder setGameinfoTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
      gameinfoTime_ = value;
      onChanged();
      return this;
    }

    // optional string extra = 15;
    private java.lang.Object extra_ = "";
    /**
     * <code>optional string extra = 15;</code>
     */
    public boolean hasExtra() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string extra = 15;</code>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string extra = 15;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string extra = 15;</code>
     */
    public Builder setExtra(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      extra_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string extra = 15;</code>
     */
    public Builder clearExtra() {
      bitField0_ = (bitField0_ & ~0x00001000);
      extra_ = getDefaultInstance().getExtra();
      onChanged();
      return this;
    }
    /**
     * <code>optional string extra = 15;</code>
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
      extra_ = value;
      onChanged();
      return this;
    }

    // optional int32 version = 16;
    private int version_ ;
    /**
     * <code>optional int32 version = 16;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 version = 16;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional int32 version = 16;</code>
     */
    public Builder setVersion(int value) {
      bitField0_ |= 0x00002000;
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 version = 16;</code>
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00002000);
      version_ = 0;
      onChanged();
      return this;
    }

    // optional string udid = 17;
    private java.lang.Object udid_ = "";
    /**
     * <code>optional string udid = 17;</code>
     */
    public boolean hasUdid() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional string udid = 17;</code>
     */
    public java.lang.String getUdid() {
      java.lang.Object ref = udid_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        udid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string udid = 17;</code>
     */
    public com.google.protobuf.ByteString
        getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string udid = 17;</code>
     */
    public Builder setUdid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
      udid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string udid = 17;</code>
     */
    public Builder clearUdid() {
      bitField0_ = (bitField0_ & ~0x00004000);
      udid_ = getDefaultInstance().getUdid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string udid = 17;</code>
     */
    public Builder setUdidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
      udid_ = value;
      onChanged();
      return this;
    }

    // optional string roleid = 18;
    private java.lang.Object roleid_ = "";
    /**
     * <code>optional string roleid = 18;</code>
     */
    public boolean hasRoleid() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional string roleid = 18;</code>
     */
    public java.lang.String getRoleid() {
      java.lang.Object ref = roleid_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        roleid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string roleid = 18;</code>
     */
    public com.google.protobuf.ByteString
        getRoleidBytes() {
      java.lang.Object ref = roleid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string roleid = 18;</code>
     */
    public Builder setRoleid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
      roleid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string roleid = 18;</code>
     */
    public Builder clearRoleid() {
      bitField0_ = (bitField0_ & ~0x00008000);
      roleid_ = getDefaultInstance().getRoleid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string roleid = 18;</code>
     */
    public Builder setRoleidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
      roleid_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:metrics.GameInfoProto)
  }

  static {
    defaultInstance = new GameInfoProto(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:metrics.GameInfoProto)
}

