// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package org.corps.bi.protobuf.common;

/**
 * Protobuf type {@code common.IntListProto}
 */
public  final class IntListProto extends
    com.google.protobuf.GeneratedMessage
    implements IntListProtoOrBuilder {
  // Use IntListProto.newBuilder() to construct.
  private IntListProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private IntListProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final IntListProto defaultInstance;
  public static IntListProto getDefaultInstance() {
    return defaultInstance;
  }

  public IntListProto getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private IntListProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              elements_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            elements_.add(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              elements_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              elements_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        elements_ = java.util.Collections.unmodifiableList(elements_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_IntListProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_IntListProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.corps.bi.protobuf.common.IntListProto.class, org.corps.bi.protobuf.common.IntListProto.Builder.class);
  }

  public static com.google.protobuf.Parser<IntListProto> PARSER =
      new com.google.protobuf.AbstractParser<IntListProto>() {
    public IntListProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IntListProto(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<IntListProto> getParserForType() {
    return PARSER;
  }

  // repeated int32 elements = 1;
  public static final int ELEMENTS_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> elements_;
  /**
   * <code>repeated int32 elements = 1;</code>
   */
  public java.util.List<java.lang.Integer>
      getElementsList() {
    return elements_;
  }
  /**
   * <code>repeated int32 elements = 1;</code>
   */
  public int getElementsCount() {
    return elements_.size();
  }
  /**
   * <code>repeated int32 elements = 1;</code>
   */
  public int getElements(int index) {
    return elements_.get(index);
  }

  private void initFields() {
    elements_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < elements_.size(); i++) {
      output.writeInt32(1, elements_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < elements_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(elements_.get(i));
      }
      size += dataSize;
      size += 1 * getElementsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.corps.bi.protobuf.common.IntListProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.protobuf.common.IntListProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.IntListProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.protobuf.common.IntListProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.IntListProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.corps.bi.protobuf.common.IntListProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.IntListProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.corps.bi.protobuf.common.IntListProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.IntListProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.corps.bi.protobuf.common.IntListProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.corps.bi.protobuf.common.IntListProto prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.IntListProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements org.corps.bi.protobuf.common.IntListProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_IntListProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_IntListProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.corps.bi.protobuf.common.IntListProto.class, org.corps.bi.protobuf.common.IntListProto.Builder.class);
    }

    // Construct using org.corps.bi.protobuf.common.IntListProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      elements_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_IntListProto_descriptor;
    }

    public org.corps.bi.protobuf.common.IntListProto getDefaultInstanceForType() {
      return org.corps.bi.protobuf.common.IntListProto.getDefaultInstance();
    }

    public org.corps.bi.protobuf.common.IntListProto build() {
      org.corps.bi.protobuf.common.IntListProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.corps.bi.protobuf.common.IntListProto buildPartial() {
      org.corps.bi.protobuf.common.IntListProto result = new org.corps.bi.protobuf.common.IntListProto(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        elements_ = java.util.Collections.unmodifiableList(elements_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.elements_ = elements_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.corps.bi.protobuf.common.IntListProto) {
        return mergeFrom((org.corps.bi.protobuf.common.IntListProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.corps.bi.protobuf.common.IntListProto other) {
      if (other == org.corps.bi.protobuf.common.IntListProto.getDefaultInstance()) return this;
      if (!other.elements_.isEmpty()) {
        if (elements_.isEmpty()) {
          elements_ = other.elements_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureElementsIsMutable();
          elements_.addAll(other.elements_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.corps.bi.protobuf.common.IntListProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.corps.bi.protobuf.common.IntListProto) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // repeated int32 elements = 1;
    private java.util.List<java.lang.Integer> elements_ = java.util.Collections.emptyList();
    private void ensureElementsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        elements_ = new java.util.ArrayList<java.lang.Integer>(elements_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 elements = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getElementsList() {
      return java.util.Collections.unmodifiableList(elements_);
    }
    /**
     * <code>repeated int32 elements = 1;</code>
     */
    public int getElementsCount() {
      return elements_.size();
    }
    /**
     * <code>repeated int32 elements = 1;</code>
     */
    public int getElements(int index) {
      return elements_.get(index);
    }
    /**
     * <code>repeated int32 elements = 1;</code>
     */
    public Builder setElements(
        int index, int value) {
      ensureElementsIsMutable();
      elements_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 elements = 1;</code>
     */
    public Builder addElements(int value) {
      ensureElementsIsMutable();
      elements_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 elements = 1;</code>
     */
    public Builder addAllElements(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureElementsIsMutable();
      super.addAll(values, elements_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 elements = 1;</code>
     */
    public Builder clearElements() {
      elements_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:common.IntListProto)
  }

  static {
    defaultInstance = new IntListProto(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:common.IntListProto)
}

