// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package org.corps.bi.protobuf.common;

public interface SimpleListProtoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated bytes elements = 1;
  /**
   * <code>repeated bytes elements = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getElementsList();
  /**
   * <code>repeated bytes elements = 1;</code>
   */
  int getElementsCount();
  /**
   * <code>repeated bytes elements = 1;</code>
   */
  com.google.protobuf.ByteString getElements(int index);
}
