// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

package org.corps.bi.metrics.protobuf;

public interface InstallProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metrics.InstallProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  java.lang.String getClientId();
  /**
   * <pre>
   *string gameId = 1;
   * </pre>
   *
   * <code>string clientId = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  java.lang.String getUserId();
  /**
   * <pre>
   *string ds = 3;
   * </pre>
   *
   * <code>string userId = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string source = 5;</code>
   */
  java.lang.String getSource();
  /**
   * <code>string source = 5;</code>
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string affiliate = 6;</code>
   */
  java.lang.String getAffiliate();
  /**
   * <code>string affiliate = 6;</code>
   */
  com.google.protobuf.ByteString
      getAffiliateBytes();

  /**
   * <code>string creative = 7;</code>
   */
  java.lang.String getCreative();
  /**
   * <code>string creative = 7;</code>
   */
  com.google.protobuf.ByteString
      getCreativeBytes();

  /**
   * <code>string family = 8;</code>
   */
  java.lang.String getFamily();
  /**
   * <code>string family = 8;</code>
   */
  com.google.protobuf.ByteString
      getFamilyBytes();

  /**
   * <code>string genus = 9;</code>
   */
  java.lang.String getGenus();
  /**
   * <code>string genus = 9;</code>
   */
  com.google.protobuf.ByteString
      getGenusBytes();

  /**
   * <code>string fromUid = 10;</code>
   */
  java.lang.String getFromUid();
  /**
   * <code>string fromUid = 10;</code>
   */
  com.google.protobuf.ByteString
      getFromUidBytes();

  /**
   * <code>string installDate = 11;</code>
   */
  java.lang.String getInstallDate();
  /**
   * <code>string installDate = 11;</code>
   */
  com.google.protobuf.ByteString
      getInstallDateBytes();

  /**
   * <code>string installTime = 12;</code>
   */
  java.lang.String getInstallTime();
  /**
   * <code>string installTime = 12;</code>
   */
  com.google.protobuf.ByteString
      getInstallTimeBytes();

  /**
   * <code>string extra = 13;</code>
   */
  java.lang.String getExtra();
  /**
   * <code>string extra = 13;</code>
   */
  com.google.protobuf.ByteString
      getExtraBytes();

  /**
   * <code>int32 version = 14;</code>
   */
  int getVersion();

  /**
   * <code>string udid = 15;</code>
   */
  java.lang.String getUdid();
  /**
   * <code>string udid = 15;</code>
   */
  com.google.protobuf.ByteString
      getUdidBytes();

  /**
   * <code>string roleid = 16;</code>
   */
  java.lang.String getRoleid();
  /**
   * <code>string roleid = 16;</code>
   */
  com.google.protobuf.ByteString
      getRoleidBytes();
}
