// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package org.corps.bi.protobuf.common;

/**
 * Protobuf type {@code common.KVProto}
 */
public  final class KVProto extends
    com.google.protobuf.GeneratedMessage
    implements KVProtoOrBuilder {
  // Use KVProto.newBuilder() to construct.
  private KVProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private KVProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final KVProto defaultInstance;
  public static KVProto getDefaultInstance() {
    return defaultInstance;
  }

  public KVProto getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private KVProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            k_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            v_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_KVProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_KVProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.corps.bi.protobuf.common.KVProto.class, org.corps.bi.protobuf.common.KVProto.Builder.class);
  }

  public static com.google.protobuf.Parser<KVProto> PARSER =
      new com.google.protobuf.AbstractParser<KVProto>() {
    public KVProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KVProto(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<KVProto> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required bytes k = 1;
  public static final int K_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString k_;
  /**
   * <code>required bytes k = 1;</code>
   */
  public boolean hasK() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required bytes k = 1;</code>
   */
  public com.google.protobuf.ByteString getK() {
    return k_;
  }

  // required bytes v = 2;
  public static final int V_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString v_;
  /**
   * <code>required bytes v = 2;</code>
   */
  public boolean hasV() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required bytes v = 2;</code>
   */
  public com.google.protobuf.ByteString getV() {
    return v_;
  }

  private void initFields() {
    k_ = com.google.protobuf.ByteString.EMPTY;
    v_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasK()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasV()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, k_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, v_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, k_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, v_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.corps.bi.protobuf.common.KVProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.protobuf.common.KVProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.KVProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.protobuf.common.KVProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.KVProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.corps.bi.protobuf.common.KVProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.KVProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.corps.bi.protobuf.common.KVProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.KVProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.corps.bi.protobuf.common.KVProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.corps.bi.protobuf.common.KVProto prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.KVProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements org.corps.bi.protobuf.common.KVProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_KVProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_KVProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.corps.bi.protobuf.common.KVProto.class, org.corps.bi.protobuf.common.KVProto.Builder.class);
    }

    // Construct using org.corps.bi.protobuf.common.KVProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      k_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      v_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_KVProto_descriptor;
    }

    public org.corps.bi.protobuf.common.KVProto getDefaultInstanceForType() {
      return org.corps.bi.protobuf.common.KVProto.getDefaultInstance();
    }

    public org.corps.bi.protobuf.common.KVProto build() {
      org.corps.bi.protobuf.common.KVProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.corps.bi.protobuf.common.KVProto buildPartial() {
      org.corps.bi.protobuf.common.KVProto result = new org.corps.bi.protobuf.common.KVProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.k_ = k_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.v_ = v_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.corps.bi.protobuf.common.KVProto) {
        return mergeFrom((org.corps.bi.protobuf.common.KVProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.corps.bi.protobuf.common.KVProto other) {
      if (other == org.corps.bi.protobuf.common.KVProto.getDefaultInstance()) return this;
      if (other.hasK()) {
        setK(other.getK());
      }
      if (other.hasV()) {
        setV(other.getV());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasK()) {
        
        return false;
      }
      if (!hasV()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.corps.bi.protobuf.common.KVProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.corps.bi.protobuf.common.KVProto) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required bytes k = 1;
    private com.google.protobuf.ByteString k_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes k = 1;</code>
     */
    public boolean hasK() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes k = 1;</code>
     */
    public com.google.protobuf.ByteString getK() {
      return k_;
    }
    /**
     * <code>required bytes k = 1;</code>
     */
    public Builder setK(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      k_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes k = 1;</code>
     */
    public Builder clearK() {
      bitField0_ = (bitField0_ & ~0x00000001);
      k_ = getDefaultInstance().getK();
      onChanged();
      return this;
    }

    // required bytes v = 2;
    private com.google.protobuf.ByteString v_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes v = 2;</code>
     */
    public boolean hasV() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes v = 2;</code>
     */
    public com.google.protobuf.ByteString getV() {
      return v_;
    }
    /**
     * <code>required bytes v = 2;</code>
     */
    public Builder setV(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      v_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes v = 2;</code>
     */
    public Builder clearV() {
      bitField0_ = (bitField0_ & ~0x00000002);
      v_ = getDefaultInstance().getV();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:common.KVProto)
  }

  static {
    defaultInstance = new KVProto(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:common.KVProto)
}

