// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package org.corps.bi.protobuf.common;

/**
 * Protobuf type {@code common.StorageKeyProto}
 */
public  final class StorageKeyProto extends
    com.google.protobuf.GeneratedMessage
    implements StorageKeyProtoOrBuilder {
  // Use StorageKeyProto.newBuilder() to construct.
  private StorageKeyProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private StorageKeyProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final StorageKeyProto defaultInstance;
  public static StorageKeyProto getDefaultInstance() {
    return defaultInstance;
  }

  public StorageKeyProto getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private StorageKeyProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            userId_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            busiFlag_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            keyFlag_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_StorageKeyProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_StorageKeyProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.corps.bi.protobuf.common.StorageKeyProto.class, org.corps.bi.protobuf.common.StorageKeyProto.Builder.class);
  }

  public static com.google.protobuf.Parser<StorageKeyProto> PARSER =
      new com.google.protobuf.AbstractParser<StorageKeyProto>() {
    public StorageKeyProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StorageKeyProto(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<StorageKeyProto> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required int64 userId = 1;
  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <code>required int64 userId = 1;</code>
   */
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 userId = 1;</code>
   */
  public long getUserId() {
    return userId_;
  }

  // required int64 busiFlag = 2;
  public static final int BUSIFLAG_FIELD_NUMBER = 2;
  private long busiFlag_;
  /**
   * <code>required int64 busiFlag = 2;</code>
   */
  public boolean hasBusiFlag() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int64 busiFlag = 2;</code>
   */
  public long getBusiFlag() {
    return busiFlag_;
  }

  // required int64 keyFlag = 3;
  public static final int KEYFLAG_FIELD_NUMBER = 3;
  private long keyFlag_;
  /**
   * <code>required int64 keyFlag = 3;</code>
   */
  public boolean hasKeyFlag() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int64 keyFlag = 3;</code>
   */
  public long getKeyFlag() {
    return keyFlag_;
  }

  private void initFields() {
    userId_ = 0L;
    busiFlag_ = 0L;
    keyFlag_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasUserId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBusiFlag()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasKeyFlag()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, userId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, busiFlag_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, keyFlag_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, busiFlag_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, keyFlag_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.corps.bi.protobuf.common.StorageKeyProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.protobuf.common.StorageKeyProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.StorageKeyProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.corps.bi.protobuf.common.StorageKeyProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.StorageKeyProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.corps.bi.protobuf.common.StorageKeyProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.StorageKeyProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.corps.bi.protobuf.common.StorageKeyProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.corps.bi.protobuf.common.StorageKeyProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.corps.bi.protobuf.common.StorageKeyProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.corps.bi.protobuf.common.StorageKeyProto prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.StorageKeyProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements org.corps.bi.protobuf.common.StorageKeyProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_StorageKeyProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_StorageKeyProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.corps.bi.protobuf.common.StorageKeyProto.class, org.corps.bi.protobuf.common.StorageKeyProto.Builder.class);
    }

    // Construct using org.corps.bi.protobuf.common.StorageKeyProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      userId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      busiFlag_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      keyFlag_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.corps.bi.protobuf.common.ToolsProto.internal_static_common_StorageKeyProto_descriptor;
    }

    public org.corps.bi.protobuf.common.StorageKeyProto getDefaultInstanceForType() {
      return org.corps.bi.protobuf.common.StorageKeyProto.getDefaultInstance();
    }

    public org.corps.bi.protobuf.common.StorageKeyProto build() {
      org.corps.bi.protobuf.common.StorageKeyProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.corps.bi.protobuf.common.StorageKeyProto buildPartial() {
      org.corps.bi.protobuf.common.StorageKeyProto result = new org.corps.bi.protobuf.common.StorageKeyProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.userId_ = userId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.busiFlag_ = busiFlag_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.keyFlag_ = keyFlag_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.corps.bi.protobuf.common.StorageKeyProto) {
        return mergeFrom((org.corps.bi.protobuf.common.StorageKeyProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.corps.bi.protobuf.common.StorageKeyProto other) {
      if (other == org.corps.bi.protobuf.common.StorageKeyProto.getDefaultInstance()) return this;
      if (other.hasUserId()) {
        setUserId(other.getUserId());
      }
      if (other.hasBusiFlag()) {
        setBusiFlag(other.getBusiFlag());
      }
      if (other.hasKeyFlag()) {
        setKeyFlag(other.getKeyFlag());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasUserId()) {
        
        return false;
      }
      if (!hasBusiFlag()) {
        
        return false;
      }
      if (!hasKeyFlag()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.corps.bi.protobuf.common.StorageKeyProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.corps.bi.protobuf.common.StorageKeyProto) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required int64 userId = 1;
    private long userId_ ;
    /**
     * <code>required int64 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>required int64 userId = 1;</code>
     */
    public Builder setUserId(long value) {
      bitField0_ |= 0x00000001;
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 userId = 1;</code>
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    // required int64 busiFlag = 2;
    private long busiFlag_ ;
    /**
     * <code>required int64 busiFlag = 2;</code>
     */
    public boolean hasBusiFlag() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 busiFlag = 2;</code>
     */
    public long getBusiFlag() {
      return busiFlag_;
    }
    /**
     * <code>required int64 busiFlag = 2;</code>
     */
    public Builder setBusiFlag(long value) {
      bitField0_ |= 0x00000002;
      busiFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 busiFlag = 2;</code>
     */
    public Builder clearBusiFlag() {
      bitField0_ = (bitField0_ & ~0x00000002);
      busiFlag_ = 0L;
      onChanged();
      return this;
    }

    // required int64 keyFlag = 3;
    private long keyFlag_ ;
    /**
     * <code>required int64 keyFlag = 3;</code>
     */
    public boolean hasKeyFlag() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 keyFlag = 3;</code>
     */
    public long getKeyFlag() {
      return keyFlag_;
    }
    /**
     * <code>required int64 keyFlag = 3;</code>
     */
    public Builder setKeyFlag(long value) {
      bitField0_ |= 0x00000004;
      keyFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 keyFlag = 3;</code>
     */
    public Builder clearKeyFlag() {
      bitField0_ = (bitField0_ & ~0x00000004);
      keyFlag_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:common.StorageKeyProto)
  }

  static {
    defaultInstance = new StorageKeyProto(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:common.StorageKeyProto)
}

