// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package org.corps.bi.protobuf.common;

public interface StringListProtoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated string elements = 1;
  /**
   * <code>repeated string elements = 1;</code>
   */
  java.util.List<java.lang.String>
  getElementsList();
  /**
   * <code>repeated string elements = 1;</code>
   */
  int getElementsCount();
  /**
   * <code>repeated string elements = 1;</code>
   */
  java.lang.String getElements(int index);
  /**
   * <code>repeated string elements = 1;</code>
   */
  com.google.protobuf.ByteString
      getElementsBytes(int index);
}
