// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package org.corps.bi.protobuf.common;

public interface IntListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.IntListProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 elements = 1;</code>
   */
  java.util.List<java.lang.Integer> getElementsList();
  /**
   * <code>repeated int32 elements = 1;</code>
   */
  int getElementsCount();
  /**
   * <code>repeated int32 elements = 1;</code>
   */
  int getElements(int index);
}
