// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package org.corps.bi.protobuf.common;

public interface KVProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.KVProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes k = 1;</code>
   */
  com.google.protobuf.ByteString getK();

  /**
   * <code>bytes v = 2;</code>
   */
  com.google.protobuf.ByteString getV();
}
